### ISSUE TITLE
setCustomVariable doesn't work for Piwik

### ISSUE THREAD

**Issue by Zefling** [angulartics/angulartics2#101]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Adding setCustomVariable on _paqwith correct data.

* **What is the current behavior?**

Not works. No data adding in _paq array with this method: 
```
angulartics2Piwik.setUserProperties()
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

On the old version, setCustomVariable  looks good.
https://github.com/angulartics/angulartics-piwik/blob/master/src/angulartics-piwik.js

```
_paq.push(['setCustomVariable', varIndex, varName, value, scope]);
```

* **Please tell us about your environment:**

- Angular version: 2.4.3
- Browser: Chrome, Firefox, IE, Edge

**Comment by Mike1707** [comment]
Any updates for this issue? I have also trouble to set custom variables with this function as I don't understand how to specify the parameter "properties" in setUserProperties(properties: any).

Piwik expects something like `_paq.push(['setCustomVariable', varIndex, varName, value, scope]);` as written above.

**Comment by chris246** [comment]
This works as desired;
`angulartics2Piwik.setUserProperties({dimension1: 'value'})`
Commit 5af6eee713d61189a6c52966986a56ff0652fabd

**Comment by Zefling** [comment]
With this, it's only possible to pass `varIndex` & `varName`, but not `value` and `scope`.
