### ISSUE TITLE
Need to set userId

### ISSUE THREAD

**Issue by inska** [angulartics/angulartics2#106]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
When setting userId outside angulartics2, any event not received at UserID View. I think setting userId in angulartics2 is need.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Should be available userId with Angulartics2, and send events with userId.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.3.x
- Browser: [Chrome Latest]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by JonnyBGod** [comment]
You should be able to set userId with ```Angulartics2.setUsername.next('USER_ID');```.

Some providers already support this such as Google Analytics provider.

**Comment by inska** [comment]
I just got that method.. Thank you!
