### ISSUE TITLE
Google Analytics social interactions

### ISSUE THREAD

**Issue by deadmantfa** [angulartics/angulartics2#107]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[*] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature for social interactions
https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions

* **What is the current behavior?**
None

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by deadmantfa** [comment]
Possible solution
```

var Angulartics2GoogleAnalytics = (function () {
    ...
   this.angulartics2.socialTrack.subscribe(function (x) { return _this.socialTrack(x.action, x.properties); });
   ...
}
Angulartics2GoogleAnalytics.prototype.socialTrack = function (action, properties) {
        if (!properties || !properties.category) {
            properties = properties || {};
            properties.category = 'Event';
        }
        if (properties.value) {
            var parsed = parseInt(properties.value, 10);
            properties.value = isNaN(parsed) ? 0 : parsed;
        }
        if (typeof ga !== 'undefined') {
            var eventOptions = {
                socialNetwork: properties.category,
                socialAction: action,
                socialTarget: properties.label,
                nonInteraction: properties.noninteraction,
                page: properties.page || location.hash.substring(1) || location.pathname,
                userId: this.angulartics2.settings.ga.userId
            };
            this.setDimensionsAndMetrics(properties);
            if (this.angulartics2.settings.ga.transport) {
                console.log('GA - transport');
                ga('send', 'social', eventOptions, { transport: this.angulartics2.settings.ga.transport });
            }
            else {
                console.log('GA - transport');
                ga('send', 'social', eventOptions);
            }
            for (var _i = 0, _a = this.angulartics2.settings.ga.additionalAccountNames; _i < _a.length; _i++) {
                var accountName = _a[_i];
                ga(accountName + '.send', 'social', eventOptions);
            }
        }
        else if (typeof _gaq !== 'undefined') {
            console.log('GA - Undefined');
            _gaq.push(['_trackEvent', properties.category, action, properties.label, properties.value, properties.noninteraction]);
        }
    };
```

**Comment by scttcper** [comment]
Please make pull request if needed.
