### ISSUE TITLE
Custom Dimensions and Custom Metrics not being  reset

### ISSUE THREAD

**Issue by deadmantfa** [angulartics/angulartics2#108]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Currently the CD and CM set are not being reset for every event

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
expected behavior is the dimensions and metrics should be reset.

The following code is triggered when the form is submitted
this.angulartics.eventTrack.next({action: 'Signup Submit', properties: {
            category: 'Login and Signup',
            label: 'Onsite',
            noninteraction: false,
            dimension3: 'Onsite',
            metric3: '1'
        }});
The following code is triggered when the the form has error

this.angulartics.eventTrack.next({action: 'Signup Fail', properties: {
                category: 'Login and Signup',
                label: 'Onsite:Passwords do not match!',
                noninteraction: false,
                dimension3: 'Onsite',
                metric2: '1'
            }});

now metric 3 is not set in the second call but is sent to GA so it should be set to null

* **What is the motivation / use case for changing the behavior?**
To get accurate analytics data

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by deadmantfa** [comment]
Possible solution could be this but then setting all 200 to null seems like pain, maybe there is a better way
    Angulartics2GoogleAnalytics.prototype.setDimensionsAndMetrics = function (properties) {
        if (ga) {
            for (var idx = 1; idx <= 200; idx++) {
                if (properties['dimension' + idx.toString()]) {
                    ga('set', 'dimension' + idx.toString(), properties['dimension' + idx.toString()]);
                } else {

                    ga('set', 'dimension' + idx.toString(), null);
                }
                if (properties['metric' + idx.toString()]) {
                    ga('set', 'metric' + idx.toString(), properties['metric' + idx.toString()]);
                } else {

                    ga('set', 'metric' + idx.toString(), null);
                }
            }
        }
    };

**Comment by adasq** [comment]
@deadmantfa, your soulution will reset all CD for pageviews, as `setDimensionsAndMetrics` is not called in `pageTrack`. Unfortunately, angularitics2 is not ready for flexible CD management during events/pageviews.

**Comment by deadmantfa** [comment]
@adasq but thats what you would want right. You dont want page1 CD to be passed to page2 as well

**Comment by Canos** [comment]
This solution is only working with hit-scoped variables. Sessions will be reset after this `undefined` set.
https://github.com/angulartics/angulartics2/pull/134/files

I suspect this undefined will remove the dimension (session-scoped) in analytics.

```
delete this.ga.dimensionsAndMetrics['0'];
delete this.ga.dimensionsAndMetrics['1'];
delete this.ga.dimensionsAndMetrics['2'];
```
