### ISSUE TITLE
How to enable analytics depending on env variable

### ISSUE THREAD

**Issue by DmitryEfimenko** [angulartics/angulartics2#109]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[ Maybe ] feature request
[ X ] question about the decisions made in the repository

* **What's the question?**
As per Quick start, I'm supposed to set third parameter in the `ga(...)` function to `none` in the dev mode:
```
ga('create', 'UA-XXXXXXXX-X', 'none'); // 'none' while you are working on localhost.
```
**How can I do it automatically depending on environment variable?**
Perhaps, 

* **What is the motivation / use case for changing the behavior?**
Inability to enable/disbale Analytics automatically between dev/prod environments would make it easy to forget about this and publish app without Analytics turned on.

* **Please tell us about your environment:**
- Angular version: 4.0.0
- Browser: all

**Comment by DmitryEfimenko** [comment]
After poking around the code I think I found the way to do it.
I just ask to please confirm (since I am not an expert in regards to Google Analytics) that's the right way and there are no visible side effects to this approach.

The only change that needs to be done is in AppComponent (or whatever root component is):
```ts
import { Component } from '@angular/core';
import { Angulartics2GoogleAnalytics, Angulartics2 } from 'angulartics2';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(angulartics2: Angulartics2, angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {
    if (!environment.production) {
      angulartics2.developerMode(true);
    }
  }
}
```
Please confirm this is the expected way of achieving desired behavior and then this issue can be closed.

**Comment by JonnyBGod** [comment]
Yes that way angulartics2 won't send events to providers.

**Comment by bill-griffin** [comment]
With version 7.1.0:
`angulartics2.settings.developerMode = !environment.production`

**Comment by gvzq** [comment]
This is the best answer for me as of today. So in recap:
```
import { Component } from '@angular/core';
import { Angulartics2GoogleAnalytics } from 'angulartics2/ga';
import { Angulartics2 } from 'angulartics2';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
   constructor(angulartics2: Angulartics2, angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {
       if (!environment.production) {
      angulartics2.settings.developerMode = !environment.production
    }
    angulartics2GoogleAnalytics.startTracking();
  }
}
```
