### ISSUE TITLE
_gaq not defined

### ISSUE THREAD

**Issue by fergusg** [angulartics/angulartics2#11]
Get an `Uncaught ReferenceError: _gaq is not defined`. (I'm using the new `analytics.js` code so I wouldn't expect it to be.)

The culprit is  at line 30 of the compiled code

```javascript
 Angulartics2GoogleAnalytics.prototype.pageTrack = function (path) {
 if (_gaq) {
   _gaq.push(['_trackPageview', path]);
  ...
```

Easy fix was to define `var _gaq;` in my `index.html`  though something like 

```javascript
   var _gaq = window._gaq || null;
   var ga = window.ga || null;
```

in the source might be better.

**Comment by MJLang** [comment]
Same issue here. The hotfix fixes it in Chrome, but Safari throws up.

**Comment by NathanWalker** [comment]
@fergusg @MJLang _gaq is loaded by `analytics.js` so as long as `analytics.js` loads before this lib, you should be good.

**Comment by jamescarter-le** [comment]
I've used the above tweak to get it running also.

**Comment by briananderson1222** [comment]
👍  isn't the analytics.js loaded asynchronously from google's code snippet?

**Comment by justme1** [comment]
I have the same problem using analytics.js as expained in 

https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet

How can I fix this issue?

**Comment by briananderson1222** [comment]
@justme1 All that second link says is that ga.js is deprecated. Doesn't say anything about the gaq global object.. The workaround above worked for me in the meantime..
