### ISSUE TITLE
Support for Adobe Analytics/Omniture

### ISSUE THREAD

**Issue by mer10z** [angulartics/angulartics2#110]
Hi there, I have a fork (https://github.com/mer10z/angulartics2) with Adobe Analytics support but I have no idea how to test it without doing a full npm publish. Can someone explain to me how I can load my forked version in my app so that I can verify that it's sending the right stuff to Adobe before I submit a PR?

**Comment by JonnyBGod** [comment]
in your testing app package.json use:

```
"angulartics2": "https://github.com/mer10z/angulartics2.git"
```

or your can link you local folder.

**Comment by mer10z** [comment]
npm install from the git repo fails because there's no version info in package.json. Was able to get the local link working. Had to import from 'angulartics2/src' since there's no index.ts in the root dir. Anyway, everything is working now, thanks.
