### ISSUE TITLE
Router Event fires before title change and page title is not correctly tracked

### ISSUE THREAD

**Issue by chouclee** [angulartics/angulartics2#112]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug: Piwik provider cannot get page title updated by router event

* **What is the current behavior?**
Page title updated by router event cannot be captured by piwik.
Piwik sends old page title. The changed title would be send in next page view.
This is due to some race conditions.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
hmm... 

In app root component
``` 
import { Title } from '@angular/platform-browser';
...

export class AppComponent  implements OnInit {
   constructor(private titleServ: Title) { }

  ngOnInit() {
    // update title
    this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        const title = routeSnapshot.data ? routeSnapshot.data['title'] : 'default title';
        this.titleServ.setTitle(title);
      }
    });
  }
}
```

However, ``angulartics2.pageTrack`` also listens to router events and piwik sends the data before I could change the title.

* **What is the expected behavior?**
Piwik send the data after updating the page title

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.4.9
- Not a Browser issue

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

fix(angulartics2-piwik.ts)
```
    // We added delay 0ms here to wait until page title has changed
    // it will be executed in next tick (I guess that's why delay 0 works)
    //  this.angulartics2.pageTrack.subscribe((x: any) => this.pageTrack(x.path, x.location));
    this.angulartics2.pageTrack.delay(0).subscribe((x: any) => this.pageTrack(x.path, x.location));
```

**Comment by stacysimpson** [comment]
Wow, there are several recent releases...we'll have to carve out some time to evaluate / upgrade. Best I can tell, things haven't changed in this space. 

We were also looking to enable route-aware page titles. Our workaround is to enable "developerMode" and trigger the page view events within our app (after setting the page title).

Seems to work fine based on initial testing.

**Comment by k-schneider** [comment]
Wouldn't this impact ALL providers?  Is there any progress or recommended work around for this?

Also I'm not sure if a delay of 0 will work in all scenarios.  We use another library (ngx-translate) that async fetches text resources like the page title and its not guaranteed that it would be updated immediately.

**Comment by chouclee** [comment]
@k-schneider  As long as you can fetch your title before NavigationEnd event, the above fix should work. To fetch everything before NavigationEnd, you can prefetch those data before navigation. (https://angular.io/guide/router#resolve-pre-fetching-component-data)

**Comment by JSMike** [comment]
Hi All,

We're seeing this impact for Google Analytics as well, as @k-schneider said I would think this impacts all providers. 

When running Angular in development mode there are additional change detection cycles so angularitics2 is picks up an event for both the initial route change and again when the title change is applied. When running in prod mode it only picks up the initial route change and doesn't send the title change event.

Just brain storming here:
For our app we've created a title service, which basically maps/filters the router events observable and applies the title set by the last child route. It's the common pattern outlined [here by Todd Motto.](https://toddmotto.com/dynamic-page-titles-angular-2-router-events)

Would it be possible to add to the Angulartics2Module.forRoot config an optional title observable that gets merged/debounced somehow with [the router observable](https://github.com/angulartics/angulartics2/blob/1abaa56923e9649e060eb0398f0146bf21324beb/src/lib/core/angular-router.ts#L25)? or maybe just have it built in to merge/debounce with the ActivatedRoute > last child > data observable?

**Comment by scttcper** [comment]
Is there an amount of time we could delay the event tracking? I don't think there's a way to subscribe to title changes.

**Comment by JSMike** [comment]
was just playing with this locally, looks like even adding a .delay(0) is enough to make it go async instead of sync so it lets the title get changed before reporting the route change.

**Comment by scttcper** [comment]
@JSMike that's good to know. I imagine there's some people that are setting the title after http calls as well... I guess that might be a good jumping off point. We'd almost have to extend the Title class to have an event emitter.

**Comment by scttcper** [comment]
To those subscribed here: let me know what you think of the PR #223 and i'll merge.

**Comment by timelf123** [comment]
LGTM
>We'd almost have to extend the Title class to have an event emitter.

This is what we did on an Angular 1 app

**Comment by paullryan** [comment]
For anyone else still struggling with this if your title gets set in the result of an observable. The best way I've found to permanently solve this is to create a title.guard.ts in which you don't return true to the guard until after your Observable property has been resolved and you've update the Title service.

```js
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { Observable } from 'rxjs/Observable';
import { URLSearchParams } from '@angular/http';
import { DataService } from 'custom-data-service';
import { Title } from '@angular/platform-browser';

@Injectable()
export class TitleGuard implements CanActivate {

  constructor(
    private _title: Title,
    private _property: PropertyService,
    private _config: ConfigService
  ) {}

  public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
    return this._property.get(route.params['id']).map(property => {
      const title = `${property.name} | ${this._config.getSettings('system.applicationName')}`;
      this._title.setTitle(title);
      return true;
    });
  }
}
```

This ensures the title is set before the event triggers in Angulartics2.
