### ISSUE TITLE
Angulartics2AdobeAnalytics account information

### ISSUE THREAD

**Issue by nkarri** [angulartics/angulartics2#117]
* **What is the current behavior?**
I have included Angulartics2 and Angulartics2AdobeAnalytics in my app.module.ts
I have also included it in my component and triggering the eventTrack function like this:
```
this._angulartics2.eventTrack.next({action: 'Clicked', properties: {linkName: activeLink.title}});
```
For testing purpose, I have added console.log in angulartics2AdobeAnalytics.js and I'm seeing it right but no network calls.

But I couldn't figure out where to provide the account information of my provider for AdobeAnalytics.
For eg. I have account ids myProj-dev, myProj-qa, myProj-prod.

**Comment by mayureshs** [comment]
nkarri - did you get this issue resolved ? we  have s_code.js included in our project that has the account information. The basic route tagging is working but I can not get the event to fire using this._angulartics2.eventTrack.next({action: 'Clicked', properties: {linkName: activeLink.title}});

**Comment by scttcper** [comment]
This looks like it should be resolved. Please include a larger code sample and we can re-open this if it still isn't working for you.

**Comment by dafabulousteach** [comment]
Where in the code should we set up the s_account information?

**Comment by arianul** [comment]
Hi there. Did you manage in the end. Where does one set up the account information?
