### ISSUE TITLE
Analytics page hit depending on environment does not work

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angulartics/angulartics2#118]
* **I'm submitting a ...**
[ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
I think this is a 'bug'. It does not work as I would expect.

* **What is the current behavior?**
when trying this: https://github.com/angulartics/angulartics2/issues/109
I still have a page hit in google analytics. What I'm searching for is that if you are in development, no google Analytics tracking would be done.
(I'm using angular-cli and do not seem to have the option to not have the ga code in my html depending on the environment)

* **What is the expected behavior?**
There should be no page hit.

* **Please tell us about your environment:**
- Angular version: 4.0.1
- Browser: all

**Comment by manuel-di-iorio** [comment]
#109 is working for me.
Have you removed `ga('send', 'pageview');` from your GA snippet (in the index.html file) ?

**Comment by scttcper** [comment]
Please make sure you have removed the pageview snippet.
