### ISSUE TITLE
Piwik documentation

### ISSUE THREAD

**Issue by Toub** [angulartics/angulartics2#120]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

Complete example and documentation on the wiki would be appreciated to make piwik work.

[Edit] here is what I did, based on https://github.com/angulartics/angulartics2/wiki/Google-Analytics. It could be used as a base for the documentation.

 I added the sandard piwik track code:

```html
  <!-- Piwik -->
  <script type="text/javascript">
    var _paq = _paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    // _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="//piwik.mydomain.com/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '11']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <!-- End Piwik Code -->
```

Note: comment "trackPageView" line as page tracking will be trigger by the angular module on route change.

app.module:
```ts
import { Angulartics2Module, Angulartics2Piwik } from 'angulartics2';
@NgModule({
	imports: [
            Angulartics2Module.forRoot([ Angulartics2Piwik ]),
            ...
```

Important: inject Angulartics2Piwik in your main component!

```ts
import { Angulartics2Piwik } from 'angulartics2';
export class AppComponent {
	constructor(
          // inject Angulartics2Piwik to initialize it!!!
          private angulartics2Piwik: Angulartics2Piwik,
	) { }
            ...
```

another.module:
```ts
import { Angulartics2Module } from 'angulartics2';
@NgModule({
	imports: [
          Angulartics2Module.forChild(),
            ...

import { Angulartics2 } from 'angulartics2';
...
constructor(
		private angulartics2: Angulartics2,
	) {
this.angulartics2.eventTrack.next({
					action: 'my-action',
					properties: {
						category: 'my-cat',
						label: 'my-label',
						value: 5
					}
				});
 }

```
* **Please tell us about your environment:**

- Angular version: 4.1.0
- Browser: [all ]
- Piwik version: 3.0.3

**Comment by DenianArthurShades** [comment]
Thanks for doing this, and somebody _please_ add it to the wiki (or at least add _some_ form of documentation for using piwik).

**Comment by Caballerog** [comment]
Thanks!

**Comment by scttcper** [comment]
We're moving away from the wiki so everyone can contribute.

If possible please make changes to the readme in the piwik directory
https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/piwik

**Comment by literalpie** [comment]
Also, to track full URLs if there is a hash (#), make sure to enable `settings=>websites=>settings=>page url fragments tracking` in the Piwik dashboard.
