### ISSUE TITLE
GA not working via GTM in IE11 and Edge only

### ISSUE THREAD

**Issue by h3llrais3r** [angulartics/angulartics2#121]
I'm not sure if this is a bug but I've been spending more than 1 day to get it working and can't seem to find a solution.

I've successfully managed to set up GTM (added the script to my index.html) and configured GTM to use the universal GA for tracking my page views.
The tag is working fine in Chrome and Firefox (they are popping op in the live view of google analytics) but I can't get it working for IE and Edge...
For some kind of reason, I never see the collect requests, so nothing is popping up in the live view.
I have already added some console statements on the `pageTrack` and `eventTrack` pushes and they are called. But the collect requests are never shown called...
Anyone experiencing the same problem?
Any help would be really appreciated.

EDIT: 1 thing do seems to work: when I add additionally the GA scrippet to the head of my index.html (of course without `ga('send', 'pageview');`, I do see the collect requests coming in...
But I don't think that's the purpose on how to solve it, isn't it?

**Comment by scttcper** [comment]
That is how you solve it.
