### ISSUE TITLE
Is it possible to change the bundle's name?

### ISSUE THREAD

**Issue by HarelM** [angulartics/angulartics2#122]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
- [x] feature request
- [x] question about the decisions made in the repository

* **What is the current behavior?**
The node_module dist package name is `core.umd.js`

* **What is the expected behavior?**
bundles package name should probably be `angulartics.core.umd.js` or anything else you think fits.

* **What is the motivation / use case for changing the behavior?**
I'm not using node_module folder as is - I'm using gulp to copy only the relevant files from there.
after copying this file it doesn't indicate where it came from and might cause conflicts if other libraries do the same.

* **Please tell us about your environment:**

- Angular version: 4.0.3
- Browser: [all]

**Comment by JonnyBGod** [comment]
You can always copy with a different file name.

**Comment by scttcper** [comment]
will be different w/ v4

**Comment by HarelM** [comment]
I ended up migrating to angular-cli and webpack so this is not an issue for me anymore.
Having said that you should probably change the name to ngx as this also works with angular 4. 😊
