### ISSUE TITLE
Pageview fires before event

### ISSUE THREAD

**Issue by MitchTalmadge** [angulartics/angulartics2#123]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Imagine two pages, A and B. On page A is a link that uses routerLink to navigate to page B. This link also sends an event to Google.

When you click the link, the pageview request is sent to Google before the event. This results in Google saying that the link was clicked on page B, when it was really clicked on page A.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

When you click the link, the event is sent and _then_ the pageview, so that Google accurately states that the event was clicked on page A.

* **What is the motivation / use case for changing the behavior?**

I cannot accurately determine which links were clicked the most on different pages because they are "clicked" on the wrong page.

* **Please tell us about your environment:**

- Angular version: 4.0.1
- Browser: Chrome 58.0.3029.110

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![image](https://cloud.githubusercontent.com/assets/8848080/26474658/870fad90-416f-11e7-9837-7a8dbe91f592.png)

**Comment by MitchTalmadge** [comment]
I have determined this is because the directive uses `EventListener` instead of `@HostListener`. [See here.](https://github.com/angulartics/angulartics2/blob/master/src/core/angulartics2On.ts#L28)

I think the proper way would be to have an `onClick` method using `@HostListener`: (And create other event methods as necessary as well)

```TypeScript
@HostListener('click')
private onClick() {
    this.eventTrack('click');
}
```

I tested this on my own directive and it behaves correctly. Event is fired first.

**Comment by JonnyBGod** [comment]
The directive is built to enable all purpose usage and for that we need to use ```EventManager``` to enable you to bind different events with it.

```@HostListener``` cannot be used for dynamically binding different events.

**Comment by degamer106** [comment]
I'm seeing this issue using v2.0.0.  Was there a fix applied in a later version?

**Comment by degamer106** [comment]
I figured it out.  For a button that has a (click) and angulartics20n on it, you need to move the angularticsXXX calls to a nested element.  So for example

```
<button
  (click)="onClick()"
>
  <div angulartics20n="..."></div>
</button>
```

**Comment by degamer106** [comment]
The previous post I put in may not work in all situations.

For example, if I have a custom component that's clickable (i.e. 400px x 400px), and the inner-most component with the angulartics2 tag is an area that's only 100px x 50px, then when I click outside of the inner-most area, GA won't be able to track it.
