### ISSUE TITLE
Naming Inconsistencies

### ISSUE THREAD

**Issue by MitchTalmadge** [angulartics/angulartics2#124]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

feature-ish

* **What is the current behavior?**

I'm finding a lot of inconsistencies in the naming scheme of this repository. For example:

Via HTML Inputs:
- [angularticsEvent] -> action
- [angularticsCategory] -> category
- [angularticsProperties]
  - label -> label 
  - value -> value

Via TypeScript:
- action -> action
- properties
  - category -> category
  - label -> label
  - value -> value

So, first thing, why is it called event in html, but action in TypeScript?
Second, why is category on its own in html, but inside properties in TypeScript?
Third, why not just create inputs for all of them? Why have a properties input at all?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

Here is an idea of how it could be structured.

Via HTML Inputs
- [angularticsEvent] -> action
- [angularticsCategory] -> category
- [angularticsLabel] -> label 
- [angularticsValue] -> value

Via TypeScript:
- action -> action
- category -> category
- label -> label
- value -> value

* **What is the motivation / use case for changing the behavior?**

Consistency. It's confusing and hard to remember the weird naming scheme.

* **Please tell us about your environment:**

- Angular version: 4.0.1
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment]
Tackled it a bit in https://github.com/angulartics/angulartics2/commit/82f5f4d38201ba7b18b601f0883c0c868692cc08
