### ISSUE TITLE
How to push a custom object into dataLayer. 

### ISSUE THREAD

**Issue by Insomniax** [angulartics/angulartics2#126]
According to the documentation the `eventTrack` accepts a `properties` object which internally is used to 
push data to dataLayer. What I noticed is that the value is documented to be a number.
I would eventually like dataLayer to push an object, for example:
`dataLayer.push(properties.customObject)`
From what I see currently this is not possible.

**Comment by dottodot** [comment]
Are far as I can tell it's not possible using angulartics2.

I've ended up creating a custom service so I can push my own data to the `dataLayer` for eccommerce purposes. Not sure how well it's going to work as yet but the data is showing, just need to test some more.

**Comment by scttcper** [comment]
If you're referring to gtm provider. This was added in #168
