### ISSUE TITLE
Critical dependency error.

### ISSUE THREAD

**Issue by mike-r-karras** [angulartics/angulartics2#128]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

I get this *warning* in build: ./~/angulartics2/~/@angular/core/@angular/core.es5.js
5915:15-102 Critical dependency: the request of a dependency is an expression
However, this also causes the SPA not to load. The error thrown is: zone_symbol__error: Error: Unexpected value '[object Object]' imported by the module 'AppModule'
    at SyntaxError.Zone

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Added the library to package.json, ran npm install, build error.

* **What is the expected behavior?**

No errors from webpack. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Angular 2.4.3, webpack 2.2.0, Node 4.7.3

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Browser: All 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment]
Please reopen if this is still an issue.
