### ISSUE TITLE
Installing in Travis fails due to postinstall script

### ISSUE THREAD

**Issue by lefos987** [angulartics/angulartics2#13]
Hey,
I installed the library locally and everything seemed to work fine. 
However, when running my build in Travis i get an error due to angulartics2 postinstall script:
<img width="786" alt="screen shot 2016-04-10 at 20 36 55" src="https://cloud.githubusercontent.com/assets/1442897/14412496/162dd576-ff5c-11e5-89f2-7a6efe0e07f4.png">

I checked the package.json and `typings` seems to point to the index file. Is this correct?

Thank you

**Comment by rigoleto** [comment]
This is an open issue for anyone not using typings - installing angulartics fails without it.

**Comment by lefos987** [comment]
Had to install typings globally in my Travis build for this to work. Was hoping to avoid doing that but works fine now
