### ISSUE TITLE
 Uncaught SyntaxError: Unexpected token import - Angular 2.4

### ISSUE THREAD

**Issue by skolli853780** [angulartics/angulartics2#132]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
Error : Uncaught SyntaxError: Unexpected token import (import { NgModule, Inject, Optional, OpaqueToken, SkipSelf } from '@angular/core';)

We are on Angular 2.4 and trying to use Angulartics2 and I am getting an error 

Uncaught SyntaxError: Unexpected token import 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

App.component.ts

import { Angulartics2GoogleAnalytics } from 'angulartics2';

  constructor(private angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {}

App.module.ts

import { Angulartics2Module, Angulartics2GoogleAnalytics } from 'angulartics2';

@NgModule({
  imports: [RouterModule.forRoot(routes ,{ useHash: true }), Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ]),
  ],

Project.config.ts

{
         name: 'angulartics2',
         path: 'node_modules/angulartics2/dist/index.js'
}

* **What is the expected behavior?**
No errors

* **What is the motivation / use case for changing the behavior?**
We are using Google Analytics to track the page views

* **Please tell us about your environment:**

- Angular version: 2.4
- Browser: [Chrome ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment]
Please try again with latest angulartics2.
