### ISSUE TITLE
Feature Request: Tack if element is in the current view

### ISSUE THREAD

**Issue by borntodesign** [angulartics/angulartics2#133]
I would like to track views on a certain DOM element for ad purposes. Is this possible?

**Comment by adamlaz** [comment]
Check out 'Scroll Tracking' 

https://angulartics.github.io/#/scroll-tracking
https://github.com/angulartics/angulartics/blob/master/samples/scroll.html

**Comment by scttcper** [comment]
Looks like there's an answer.
Please comment if this should re-open.
