### ISSUE TITLE
Not sending route changes

### ISSUE THREAD

**Issue by sGerli** [angulartics/angulartics2#143]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
I installed it and then I tried testing it but it isn't reporting anything back to GA, no route change and no initial route.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Track initial route and all route changes

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.3.4
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I am using an extra route module with all the routes and an export:
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { Angulartics2Module, Angulartics2GoogleAnalytics } from 'angulartics2'; // I've also tried this in the app.module.ts

// all of the other imports

const routes: Routes = [
  
  {
    path: 'app',
    component: MainAppComponent,
    canActivate: [AuthGuard],
} // and all of my other routes
];

@NgModule({
  imports: [RouterModule.forRoot(routes),
    Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ])],
  exports: [RouterModule],
  providers: [MyProviders]
})
export class AppRoutingModule { }

```

And then this module is imported in the `app.module.ts`.

GA debugger:
```
Initializing Google Analytics.
analytics_debug.js:10 Running command: ga("create", "UA-XXXXXXXX-X", "auto")
analytics_debug.js:10 Creating new tracker: t0
analytics_debug.js:10 Auto cookieDomain found: "mydomain.com"
analytics_debug.js:10 Registered new plugin: ga(provide, "render", Function)
```

**Comment by scttcper** [comment]
Are you loading the analytics in the root component?
```ts
import { Angulartics2GoogleAnalytics } from 'angulartics2';
@Component({
  selector: 'app',
  template: `<router-outlet></router-outlet>` // Or what your root template is.
})
export class AppComponent {
  constructor(angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {}
}
```

**Comment by sGerli** [comment]
Oops, no I didn't, that fixed the issue. Thanks
