### ISSUE TITLE
Link in package is to http://angulartics.github.io/ should be http://angulartics2.github.io/

### ISSUE THREAD

**Issue by alignsoft** [angulartics/angulartics2#149]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

The link in the package that shows up in npm or yarn outdated is to http://angulartics.github.io/ (which is currently at version 1.4). The link should be to http://angulartics2.github.io/

It's confusing when an update is available and the link to the release notes is to the wrong repo.

**Comment by scttcper** [comment]
Fixed in next branch, Thanks!
