### ISSUE TITLE
Angulartics2Facebook is not tracking page views

### ISSUE THREAD

**Issue by pankhuri** [angulartics/angulartics2#150]
I am trying to use both Angulartics2GoogleAnalytics and Angulartics2Facebook on my site. I can see GA tracking calls when I inspect, but I can't see any Facebook pixel call. I have followed the same steps as GA. Let me know what can be done. It's super critical.

I just need to track page views and no custom events for now. 

**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pankhuri** [comment]
Hey can anybody help me on this?

**Comment by brocgailit** [comment]
By default Facebook will track the push state for SPA's, so be sure not to remove `fbq('track', 'PageView')` from your tracking code as you would for Google Analytics.

[Tagging Single Page Applications with the Facebook Pixel](https://developers.facebook.com/ads/blog/post/2017/05/29/tagging-a-single-page-application-facebook-pixel/)
