### ISSUE TITLE
Global Site Tag support?

### ISSUE THREAD

**Issue by byrondover** [angulartics/angulartics2#155]
Is support for gtags on the roadmap?

<https://developers.google.com/analytics/devguides/collection/gtagjs/>

**Comment by JonnyBGod** [comment]
I am not using it atm. It should be easier for someone more familiar with gtagjs to implement an interface for it.

You might be a good candidate for a try at it. :) Let me know if you need some help.

**Comment by i049382** [comment]
From what i have tried, the events do not seem to be captured.... i assume there was to be no change to the way they are invoked?
