### ISSUE TITLE
Capture outbound links

### ISSUE THREAD

**Issue by tschaka1904** [angulartics/angulartics2#156]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature or documentation

* **What is the expected behavior?**
A functionality to capture the outbound pages.

* **What is the motivation / use case for changing the behavior?**
Capturing more data.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by karllhughes** [comment]
Could you do this by [adding an event](https://github.com/angulartics/angulartics2#tracking-events)? Or are you hoping for something automatic in the library?
