### ISSUE TITLE
Exception Tracking for Google Analytics

### ISSUE THREAD

**Issue by acuntex** [angulartics/angulartics2#160]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Would it be possible to integrate exception logging for google analytics?

https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

**Comment by kirevey** [comment]
@acuntex This is already possible with the ga provider.
https://github.com/angulartics/angulartics2/blob/35575c219ad6fca28b0e26855211aad35d8e4079/src/providers/ga/angulartics2-ga.ts#L108-L134
