### ISSUE TITLE
webpack library name config might be wrong

### ISSUE THREAD

**Issue by jonyeezs** [angulartics/angulartics2#161]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a potential bug

* **What is the current behavior?**

https://github.com/angulartics/angulartics2/blob/master/webpack.config.js#L28
```json
library: 'ngx-translate-core'
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I'm not 100% sure how this is reuse a webpack library. Unfortunately, this is more of a "spidey-sense".

* **What is the expected behavior?**

Would expect it to be `library: 'angulartics2'`

* **What is the motivation / use case for changing the behavior?**

Affect people who might be using umd webpack libraries?

* **Please tell us about your environment:**

- Angular version: 4.x.x
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment]
fixed on next branch, thanks see #154
