### ISSUE TITLE
Support for Angular 5.x

### ISSUE THREAD

**Issue by wosevision** [angulartics/angulartics2#165]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[X] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Reporting bug: Angulartics2 breaks on Angular 5+ (current version 5.0.0-rc.5) due to the deprecation of `OpaqueToken`. Requesting feature: replace `OpaqueToken` with its generically typed drop-in replacement, `InjectionToken<T>`

* **What is the current behavior?**
Build fails when including this module in Angular projects >= 5.0.0:

```
node_modules/angulartics2/dist/index.d.ts(1,31): error TS2305: Module '"/.../@angular/core/core"' has no exported member 'OpaqueToken'.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Minimal repro: http://plnkr.co/edit/ASimoY1mZuSzLggxkR7t?p=preview

* **What is the expected behavior?**
Use `InjectionToken` instead of `OpaqueToken`.

* **What is the motivation / use case for changing the behavior?**
Compatibility with Angular 5.

**Comment by scttcper** [comment]
The latest version is already using InjectionToken https://github.com/angulartics/angulartics2/blob/master/src/index.ts

**Comment by wosevision** [comment]
@scttcper My apologies, I did a reinstallation with the version number explicitly specified and it definitely is working.

You can close this one whenever time permits!

**Comment by prinzt** [comment]
Hi,
there is still a small problem. npm shrinkwrap breaks with angular v5.0.0 and angulartics2 v3.4.7 because of angulartics peerDependencies.

```
npm ERR! peer invalid: @angular/common@^4.4.0, required by angulartics2@3.4.7
npm ERR! peer invalid: @angular/core@^4.4.0, required by angulartics2@3.4.7
npm ERR! peer invalid: @angular/router@^4.4.0, required by `angulartics2@3.4.7`
```


A quick fix would be to define them like ">=4.4.0"

**Comment by scttcper** [comment]
@prinzt that should just be a warning but I don't normall use npm shrinkwrap. I've pushed a fix that will be deployed whenever travis decides to start working again.

**Comment by prinzt** [comment]
Hi Scott,
thanks for the quick fix.
Waiting for travis  :-)
