### ISSUE TITLE
npm - missing .js files

### ISSUE THREAD

**Issue by NathanWalker** [angulartics/angulartics2#17]
Looks like with `1.0.3` just published, it's now missing the src/providers/*.js files...
the .js.map files are there but no .js files resulting in errors.
From a fresh install with latest:
![screen shot 2016-04-14 at 4 10 04 pm](https://cloud.githubusercontent.com/assets/457187/14546603/783d0352-025b-11e6-9eb8-57716236241f.png)

**Comment by NathanWalker** [comment]
I believe the reason is because the `.ts` is missing in this:
https://github.com/angulartics/angulartics2/blob/master/tsconfig.json#L22-L25

**Comment by JonnyBGod** [comment]
Yes just realised it. Not sure why but ```tsc -d``` is not creating the .js files.
Tried your tip but no luck.

**Comment by NathanWalker** [comment]
That PR will fix it... definitely generates the .js for those files now for me locally.

**Comment by NathanWalker** [comment]
Btw, if you want to add me as collaborator here and on npm for this, I can help with this kind of stuff in the future.

**Comment by JonnyBGod** [comment]
Sure will ask for you to be added. Just need to ask angularitics guys.
Thanks for your help.

**Comment by JonnyBGod** [comment]
Files are still missing from latest build.

**Comment by NathanWalker** [comment]
They are still not there, I see that with 1.0.4, very strange. Are they there when you build and before you publish?

**Comment by NathanWalker** [comment]
Basically:
```
npm run build
```

Look in `src/providers`, are the .js files there?

If yes, bump version, then:
```
npm publish
```

Should do it.

If there are not there, then there must be errors resulting when running `npm run build` that are preventing the provider files from compiling?

**Comment by JonnyBGod** [comment]
```npm run build ``` is working locally

Release process should work with semantic-release in travis.

**Comment by NathanWalker** [comment]
I think this: https://github.com/angulartics/angulartics2/pull/19 will finally solve it.

**Comment by JonnyBGod** [comment]
I am up for trying any idea at this point. :/

**Comment by NathanWalker** [comment]
Ok I didn't know you are relying on sematic release, you will need to change this then in `package.json`:
```
"semantic-release": "semantic-release pre && npm publish && semantic-release post"
```

I would have added that in my PR... anyway just change that ^ to this...

```
"semantic-release": "npm run build && semantic-release pre && npm publish && semantic-release post"
```

pretty sure that would do it

**Comment by JonnyBGod** [comment]
Oh yes that should be it.

Thanks again.

**Comment by NathanWalker** [comment]
Well wow still not it. Ok it takes a lot, and I mean a lot to make me quit, so we will solve this thing... maybe it needs this:

```
"semantic-release": "semantic-release pre && npm run build && npm publish && semantic-release post"
```

May require `pre` be first.

**Comment by JonnyBGod** [comment]
trying it.

**Comment by NathanWalker** [comment]
Hooray!! it worked!

**Comment by NathanWalker** [comment]
Well we both learned something very important 👍

**Comment by JonnyBGod** [comment]
Great!! Yes now I can fix two other libraries. Big thanks.

**Comment by NathanWalker** [comment]
I need to start using `semantic-release` myself but yeah I guess it's paramount that `pre` be the first out the gate to execute (which makes sense if you think about it)... anyhow, this looks much better now!
And I love this lib, so def wanna make it as tight as possible!

**Comment by JonnyBGod** [comment]
Sorry about these bugs... I am very new to all this (angular2, observables, typescript...) learning all atm. I am bound to make these mistakes at first. Good to have some help :)

**Comment by NathanWalker** [comment]
N/p at all, I'm new to them as well and have been making mistakes myself in several places.
The idiosyncrasies with publishing and developing the lib make for some serious confusion at times.
We're getting there! ... together 👍

**Comment by JonnyBGod** [comment]
Added you as collaborator.

**Comment by NathanWalker** [comment]
Thx! I'll help tighten and review when I can and as always would put stuff up for review before making any changes, cheers!

**Comment by JonnyBGod** [comment]
Can you talk (https://gitter.im/angulartics/angulartics2) one minute? I would like to run an issue through you.
