### ISSUE TITLE
Angulartics2GoogleAnalytics in v3.4.3 has no "setUsername" function.

### ISSUE THREAD

**Issue by acuntex** [angulartics/angulartics2#171]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Somehow the setUsername function got removed in https://github.com/angulartics/angulartics2/commit/37fad11187676d0857b0b8e49a6fa0c4eac0648c in the file angulartics2-ga.ts

I'm guessing this was not intended.

Edit: Sorry for the title edits, somehow npm always installed the prelease version.

**Comment by scttcper** [comment]
should continue using 3.3.0 for now on latest

**Comment by acuntex** [comment]
That's what I'm doing ;-)

But is it intended or unintended?

**Comment by scttcper** [comment]
Oh you're right it is missing.

**Comment by scttcper** [comment]
back in 3.4.7
