### ISSUE TITLE
Inconsistent versions with yarn / npm outdated 3.5.0 wanted, 3.3.0 latest

### ISSUE THREAD

**Issue by alignsoft** [angulartics/angulartics2#174]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
running yarn outdated returns the following:

Package                    Current     Wanted Latest   Package Type    URL
angulartics2             3.3.0           3.5.0     3.3.0    dependencies    http://angulartics.github.io/

Couple of issues - Latest should be 3.5 (i think) - it appears to be in npm, but presumably not dist-tagged as latest

Second - the URL is for the AngularJS package, it should be for the Angular package, and you have to search for the correct repo in order to get here.

* **What is the expected behavior?**

Package         Current   Wanted Latest  Package Type   URL
angulartics2  3.3.0        3.5.0     3.5.0    dependencies   https://github.com/angulartics/angulartics2

* **What is the motivation / use case for changing the behavior?**

I believe the current behavior is at best confusing, and at worst incorrect.

* **Please tell us about your environment:**

- Angular version: 4.4.6
- Browser: [all - Chrome on Mac OS X for Dev ]

**Comment by scttcper** [comment]
latest is 3.3.0
testing refactoring which is being published on next

Link to landing page is fixed on https://github.com/angulartics/angulartics2/tree/next

**Comment by scttcper** [comment]
The pr for v4 on latest is open.
