### ISSUE TITLE
tag manager ecommerce 

### ISSUE THREAD

**Issue by dottodot** [angulartics/angulartics2#180]
One part of gtm enhanced ecommerce is measuring product views where you only send the ecommerce properties i.e

```
// Measure a view of product details. This example assumes the detail view occurs on pageload,
// and also tracks a standard pageview of the details page.
dataLayer.push({
  'ecommerce': {
    'detail': {
      'actionField': {'list': 'Apparel Gallery'},    // 'detail' actions have an optional list property.
      'products': [{
        'name': 'Triblend Android T-Shirt',         // Name or ID is required.
        'id': '12345',
        'price': '15.25',
        'brand': 'Google',
        'category': 'Apparel',
        'variant': 'Gray'
       }]
     }
   }
});
```
And they advise the following tag configuration. 

Tag type : Universal Analytics
Track type : Pageview
Enable Enhanced Ecommerce Features: true
Use Data Layer: true
Trigger: event equals gtm.dom

I can't quite work out how I should do this in angulartics2

**Comment by scttcper** [comment]
What do you have right now? 
Have you activated https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/ga-enhanced-ecom

**Comment by dottodot** [comment]
I was trying to use tag manager rather than the standard GA, where you push to the dataLayer, so at the moment I add my own method to push to the datalayer as angulartics2 doesn't have a way to do that.

**Comment by scttcper** [comment]
https://github.com/angulartics/angulartics2/blob/master/src/lib/providers/gtm/angulartics2-gtm.ts#L44-L68
