### ISSUE TITLE
 Angulartics2Module.forRoot() called twice. Lazy loaded modules should use Angulartics2Module instead.

### ISSUE THREAD

**Issue by dottodot** [angulartics/angulartics2#181]
I've add the following in my app.module

```
  Angulartics2Module.forRoot([Angulartics2GoogleTagManager]),
```
but if I them import and export `Angulartics2Module` in my shared.module I get the following error

> Error: Uncaught (in promise): Error: Angulartics2Module.forRoot() called twice. Lazy loaded modules should use Angulartics2Module instead.
> Error: Angulartics2Module.forRoot() called twice. Lazy loaded modules should use Angulartics2Module instead.
>     at new Angulartics2Module (angulartics2.module.js:8)
>     at _createClass (core.js:10622)
>     at _createProviderInstance$1 (core.js:10596)
>     at initNgModule (core.js:10549)
>     at new NgModuleRef_ (core.js:11792)
>     at createNgModuleRef (core.js:11782)
>     at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14092)
>     at NgModuleFactory_.create (core.js:15216)
>     at MapSubscriber.eval [as project] (router.js:4444)
>     at MapSubscriber._next (map.js:79)
>     at new Angulartics2Module (angulartics2.module.js:8)
>     at _createClass (core.js:10622)
>     at _createProviderInstance$1 (core.js:10596)
>     at initNgModule (core.js:10549)
>     at new NgModuleRef_ (core.js:11792)
>     at createNgModuleRef (core.js:11782)
>     at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14092)
>     at NgModuleFactory_.create (core.js:15216)
>     at MapSubscriber.eval [as project] (router.js:4444)
>     at MapSubscriber._next (map.js:79)
>     at resolvePromise (zone.js:824)
>     at resolvePromise (zone.js:795)
>     at eval (zone.js:873)
>     at ZoneDelegate.invokeTask (zone.js:425)
>     at Object.onInvokeTask (core.js:4620)
>     at ZoneDelegate.invokeTask (zone.js:424)
>     at Zone.runTask (zone.js:192)
>     at drainMicroTaskQueue (zone.js:602)
>     at <anonymous>

**Comment by scttcper** [comment]
probably related to #179

**Comment by scttcper** [comment]
try v4.0.1

**Comment by smoke** [comment]
This should definitely be fixed by https://github.com/angulartics/angulartics2/pull/179

**Comment by dottodot** [comment]
yes v4.0.1 seems to fix that
