### ISSUE TITLE
Route changes and events don't report

### ISSUE THREAD

**Issue by johnestes4** [angulartics/angulartics2#195]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Right now, for every page it only reports the base directory (just "/"). So it is reporting back to Clicky with each change, but it doesn't seem to be sending any actual route info. Events aren't working either.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Track route changes and custom events

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.4.6
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I think I've got everything imported properly in app.module and app.component.

app.module:

```
//other imports

import { ROUTES } from './app.routes';
import { Angulartics2Module } from 'angulartics2';
import { Angulartics2Clicky } from 'angulartics2/clicky';

@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...
    RouterModule.forRoot(ROUTES, {useHash: true}),
    Angulartics2Module.forRoot([Angulartics2Clicky]),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

app.component:
```
//other imports

import { Angulartics2Clicky } from 'angulartics2/clicky';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [AuthService, UserService, MessageService]
})
export class AppComponent implements OnInit {
  ...
  constructor(
    private auth: AuthService,
    private messageService: MessageService,
    private userService: UserService,
    private router: Router,
    angulartics2Clicky: Angulartics2Clicky,
  ){ }
}
```

**Comment by scttcper** [comment]
It could be because you're using hash based routing. `{useHash: true}`

**Comment by johnestes4** [comment]
Removing the hash does fix the route reporting, although the custom events still aren't tracking. Any ideas on that front? I'm using the exact example code from the Clicky documentation.

**Comment by scttcper** [comment]
maybe ping @nicholascelestin i have no idea

**Comment by nicholascelestin** [comment]
I just generated a new Angular project and copy-pasted the event code from the Clicky readme, and it seems to be working fine.

Are you testing in a separate (incognito) browser session and viewing incoming events from the Clicky spy panel? Can you provide a full plunkr?

**Comment by johnestes4** [comment]
Turns out that was a browser issue. I guess my Chrome was blocking it somehow (it wound up working fine in Edge), so I'm going to chalk it up to my dumb errors.

Thanks for the help, everyone.
