### ISSUE TITLE
Install specific version

### ISSUE THREAD

**Issue by jenb34** [angulartics/angulartics2#198]
Hi,

I've noticed that while trying to install a specific version e.g "npm install angulartics2@3.3.0" that most versions aren't valid install targets? Is there a way to install a specific version?

Thanks

**Comment by scttcper** [comment]
That has less to do with angulartics and more to do with npm. It should be fine

**Comment by jenb34** [comment]
Our company only approves certain versions of components though, so we need to be able to stick to one version and when npm install is run then it should install this specific version but at the moment there is no way to install v3.3.0 for example? I receive an npm error with valid install target versions but they are all v1 and below?

**Comment by scttcper** [comment]
`npm info angulartics2` should list all available versions including 3.3.0. If they aren't available for you, your work is possibly blocking npm or running its own self hosted version.
