### ISSUE TITLE
Publish latest when possible?

### ISSUE THREAD

**Issue by NathanWalker** [angulartics/angulartics2#20]
@JonnyBGod I pushed up beta.16 compatibility to master just a few minutes ago. Since I'm not a collaborator on npm, it may not have bumped/published. If you could do so as soon as possible would be great. Thanks!  Trying to update the seed project and need this update.

**Comment by JonnyBGod** [comment]
@NathanWalker You can publish by yourself. it is automatic on every commit. Only thing you have to do it use a commit message with "fix" format like ```fix(package.json): update dependencies.``` this will trigger a new release.

I realise it is not common to use a fix message for an update but it works well for now with current CI implementation.

I used ```fix(Build): rebuild for new release.``` several times before just to trigger a release.

**Comment by NathanWalker** [comment]
Ok nice, just tried it now. we will see.
