### ISSUE TITLE
Baidu Analytics Provider Is Outdated

### ISSUE THREAD

**Issue by Roman-Lo** [angulartics/angulartics2#205]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Baidu analytics is not working.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

The current implementation of Baidu Analytics is outdated. The latest official documentation of Baidu Analytics shows that it uses the global variable `_hmt` but not `hmt` (I'm not sure if the previous one is `hmt`). It is quite easy to fix this, just replace all the `hmt` to `_hmt`. 
Also, I think I found a typepo in the baidu provider as well:
```
// line #14 - /src/lib/providers/baidu/angulartics2-baidu.ts
hmt.push(['_ setAutoPageview', false]);
// it should be '_setAutoPageview', and there should not have an extra space in it. :P
```
I already got this fixed in my app (i created a new provider by myself currently), and if you need help about this, just tell me and i can fire a merge request to this repo.

**Comment by scttcper** [comment]
all the providers are maintained by contributors, please pr

**Comment by Roman-Lo** [comment]
OK! PR's ready!
