### ISSUE TITLE
Can't resolve 'rxjs/operators/filter'

### ISSUE THREAD

**Issue by celsomtrindade** [angulartics/angulartics2#208]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I've started a new project (using the environment described below) and I'm having some errors when running `ng serve` or `ng build`.

> Module not found: Error: Can't resolve 'rxjs/operators/filter' in  '{my project folder}\node_modules\angulartics2'
resolve 'rxjs/operators/filter' in '{my project folder}\node_modules\angulartics2'

When I change [this line](https://github.com/angulartics/angulartics2/blob/master/src/lib/core/angulartics2.ts#L4) to:

    import { filter } from 'rxjs/add/operator/filter';

Then the error disapear and the compilation works as expected.

* **Please tell us about your environment:**

- Angular version: 5.1.2
- Angular CLI: 1.6.2
- Rxjs: 5.4.3

**Comment by leo6104** [comment]
Please update to rxjs >= 5.5.2.

**Comment by celsomtrindade** [comment]
@leo6104  Thanks.

But.. weird.. I've just started the project and also used `npm update package` and it didn't got the latest version..

But it solved the issue.
