### ISSUE TITLE
Installation Issue with "angular2-webpack-starter"

### ISSUE THREAD

**Issue by bhargavweb** [angulartics/angulartics2#21]
Hi,
I am using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter).
I tried installation steps from [here](https://github.com/angulartics/angulartics2).

I got the following error:
`./~/angulartics2/src/core/angulartics2.js
Module not found: Error: Cannot resolve module 'angular2/platform/common'`

Angular2 version in use : 2.0.0-beta.15

**Comment by NathanWalker** [comment]
You'll need to update to beta.16 or higher. Angular is at beta.17 now.
