### ISSUE TITLE
Basic documentation for providers

### ISSUE THREAD

**Issue by hassanasad** [angulartics/angulartics2#213]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[ X ] feature request
[ ] question about the decisions made in the repository

Will it be possible for anyone in the community to provide some basic setup documentation for providers. The package has good tutorial for Google Analytics, i wish there was something similar for intercom, mixpanel etc as well.

**Comment by scttcper** [comment]
The providers and their docs are pretty much community driven. I would like to see docs for them though

**Comment by figuerres** [comment]
can we get a few hints please, i want to use Microsoft AI

do i need to do an npm install of the Microsoft script package ?
i do not see it in this package and i do not see a reference to it.

do we set key values and init the package as if it was used directly ??

it looks like that is it but i am just guessing....

**Comment by ngoswald11404** [comment]
I was also hoping for similar documentation on **Adobe analytics (Omniture) setup** as well. So far I have provisioned an analytics account and need some starting point for setting up analytics connection to my application.

**Comment by ChaudhryAtif** [comment]
> 
> 
> I was also hoping for similar documentation on **Adobe analytics (Omniture) setup** as well. So far I have provisioned an analytics account and need some starting point for setting up analytics connection to my application.

Hey @ngoswald11404, were you able to figure out how to add adobe analytics?
