### ISSUE TITLE
Is there a way to turn off it by environment variable?

### ISSUE THREAD

**Issue by loganfreeman** [angulartics/angulartics2#214]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[* ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Is there a way to turn off it by environment variable?
* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by k-schneider** [comment]
You're going to be told to set "developerMode" mode to true when you import Angulartics2Module.

`Angulartics2Module.forRoot([providers], {
  developerMode: True
}),`

I'm also evaluating this library right now and I think this only stops page view tracking. Is there any way to stop event tracking?

**Comment by k-schneider** [comment]
Actually I came up with something reasonable.  Instead of injecting each provider into my root component I am instead using the Injector service to resolve them only when environment.production=true.

**Comment by loganfreeman** [comment]
How about not importing the module if isDevMode() ?

**Comment by loganfreeman** [comment]
seems not a good idea. then the directive can be used

**Comment by switch87** [comment]
I have forked the project to make a version without static javascript in the index.html file. This gives the possibility to not including it at all if in development mode.
Throwback is the code will be loaded only after bootstrapping angular. At the moment it only works for Google Analytics, but feel free to open a issue for the services you use (or to do a pull request).
the Google analytics version can already be installed using 'ngm install ngx-analytics'

https://github.com/SnakeByteDevelopment/angulartics2

**Comment by sleicht** [comment]
@switch87 Why not push this back to this project?

**Comment by scttcper** [comment]
@sleicht He did. see https://github.com/angulartics/angulartics2/pull/216 It also raises problems with SSR.

I can work on this this week and stop all tracking from a setting.

**Comment by sleicht** [comment]
Thanks for the heads-up.

**Comment by scttcper** [comment]
Looking for feedback on #224

Basically the event emitters are filtered at the provider level and when developer mode is true no events will get through.
