### ISSUE TITLE
How do I send "label" for google analytics? 

### ISSUE THREAD

**Issue by arvindtheace** [angulartics/angulartics2#22]
In the example given, only event and category is given. How can I send Label? Right now, when I see the  GA dashboard, the Event Label is "not set"

**Comment by JonnyBGod** [comment]
You can use ```angularticsProperties``` for this like:

```
<div angulartics2On="click" angularticsEvent="DownloadClick" angularticsProperties="{label: 'Your_label_here'}"></div>
```

**Comment by Hongbo-Miao** [comment]
Just point out the correct use is:

div angulartics2On="click" angularticsEvent="DownloadClick" angularticsProperties="({label: 'Your_label_here'})"></div>

**Comment by hunhavoc** [comment]
The correct form now is:
<div
    angulartics2On="click"
    angularticsEvent="DownloadClick" 
    [angularticsProperties]="{label: 'Your_label_here'}">
</div>

**Comment by Shitashi** [comment]
I am having an issue where this is not sending the label.  It seems to be posting to 'targetProperties' the label value when I use the correct syntax but not as 'label'.  I also seem to have this issue regardless of if the label key is surround in quotes or not.  I've also tried wrapping the label data in parenthesis and this doesn't seem to work.  Is this a known issue in the latest build?

`<button type="button" angulartics2On="click" angularticsEvent="ng click" angularticsCategory="ng Onboarding" [angularticsProperties]="{'label': 'ng Skip'}">
Skip to sign in
</button>
`

**Comment by MatthewDaniels** [comment]
To compliment Shitashi's issue above, this is a problem with the GTM Provider and a pull request has been generated with the appropriate fix.

**Comment by Shitashi** [comment]
Updating my build to use v1.6.1 which includes the pull request Matt submitted appears to fix this problem.  Thank you very much Matt!
