### ISSUE TITLE
Google Analitics, CID (client id) is not set

### ISSUE THREAD

**Issue by martinduris** [angulartics/angulartics2#222]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When i set username, for example:
`this.angulartics2.setUsername.next(this.user.id);`
to google analytics is CID (client id) always send with 'default' value like: 
`cid:1611570979.1516779780`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
I expected that CID send to google analytics would be username which i had set.

* **What is the motivation / use case for changing the behavior?**
Same users who visits my site after login would be always in Google Analytics analyzed as same users .

* **Please tell us about your environment:**
Angular v.5.1.x, npm 4.2.0, nodej 7.10.1, angualristic2 v.4.6.3, browser chrome

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by vrih** [comment]
Looks like https://github.com/angulartics/angulartics2/commit/c56784589043450ebfa94d745bd037b3d8a0630b might resolve this.

**Comment by sakiv** [comment]
The same issue is also happening with Google Tag Manager provider. Client Id is not being sent correctly.
