### ISSUE TITLE
gtag.js support?

### ISSUE THREAD

**Issue by janpio** [angulartics/angulartics2#225]
Google Analytics seems to have switched from `analytics.js` to `gtag.js` as the default tracking code for new Google Analytics properties. 

The code now looks like this:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxxxx-x"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'xxxxxxxxxx-x');
</script>
```
More information also here: https://developers.google.com/analytics/devguides/collection/gtagjs/

The [Google Analytics](https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/ga) instructions don't mention this. 

Does `angulartics` support this new code? If so, how exactly?

**Comment by scttcper** [comment]
https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/gtm

**Comment by janpio** [comment]
Huh, so Google is pushing Google Tag Manager by default when using Google Analytics now? Strange...

**Comment by scttcper** [comment]
I don't think its a replacement. I think its bigger and has more features and loads analytics.js inside of it.

**Comment by janpio** [comment]
Which makes it even stranger that this is now the default code snippet that is shown to Google Analytics users. But I created a PR that tries to help users having the same problem a bit.

**Comment by scttcper** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/
