### ISSUE TITLE
"Using without a Router", "@angular/router must still be installed! ..." not true for me

### ISSUE THREAD

**Issue by janpio** [angulartics/angulartics2#226]
https://github.com/angulartics/angulartics2#using-without-a-router says

> `@angular/router` must still be installed! However, it will not be used.

This turned out not to be true for me. 

First I naively installed angulartics2 with the default instructions (on a project that is not using the Angular router yet), which gave me this error:

![image](https://user-images.githubusercontent.com/183673/35875352-43ee71a2-0b6f-11e8-8c1f-5eaec435ba8e.png)

Then I found https://github.com/angulartics/angulartics2#using-without-a-router and replaced the import to `Angulartics2RouterlessModule` and now everything is "working".

Why, where and how do I still need the router?

**Comment by janpio** [comment]
Ok, it's not working at all with the `RouterlessModule` for me :/

**Comment by scttcper** [comment]
You still need router installed.

**Comment by janpio** [comment]
Seems I really had the `@angular/router` package installed, but never used and so wasn't aware.
