### ISSUE TITLE
`ERROR in src/app/app.module.ts(9,46): error TS2307: Cannot find module 'angulartics2/routerlessmodule'`

### ISSUE THREAD

**Issue by janpio** [angulartics/angulartics2#230]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

When using https://github.com/angulartics/angulartics2#using-without-a-router in a project I get on `ng serve`:

```
webpack: Compiling...
ERROR in src/app/app.module.ts(9,46): error TS2307: Cannot find module 'angulartics2/routerlessmodule'. 72% optimizing                                                          73% basic module optimization                                                                                                                                                 Date: 2018-02-06T18:38:15.063Z • Hash: a3b8b355bad1b9c8b553 • Time: 3152ms
3 unchanged chunks
chunk {main} main.bundle.js (main) 238 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 11.3 MB [initial] [rendered]

webpack: Compiled successfully.
```

Interestingly enough this still compiles and can normally be run.

* **What is the expected behavior?**

No error message, still working.

**Comment by janpio** [comment]
While this seems to be fine in `ng serve`, `ng build -prod` is not so happy about it:

```
λ ng build -prod
Date: 2018-02-06T18:42:07.229Z
Hash: 0c49dd5ced8789f4fa7f
Time: 20879ms
chunk {0} styles.77855a6a813361f197d5.bundle.css (styles) 360 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.9d07561b59257af76b95.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in app\app.module.ts(30,5): Error during template compile of 'AppModule'
  Could not resolve angulartics2/routerlessmodule relative to C:/Projects/.../src/app/app.module.ts..
src/app/app.module.ts(9,46): error TS2307: Cannot find module 'angulartics2/routerlessmodule'.
```

:(

**Comment by janpio** [comment]
Interesting, just noticed that the initial build with `ng serve` also fails and shows the same error message  in the browser:

![image](https://user-images.githubusercontent.com/183673/35878188-ca113d70-0b77-11e8-89ed-cdcc28035bbd.png)

Only subsequent builds succeed.

**Comment by marcushultgren** [comment]
I have the same issue. Did you get it to work?

**Comment by janpio** [comment]
Don't think so, I think I went back to the other method of using it with a router...

**Comment by scttcper** [comment]
Make sure you're using typescript > 2.6.x

**Comment by gdlm91** [comment]
I'm having a similar issue. When I build with `ng serve` I don't see any error in console, but building with `ng prod` causes this:

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'Angulartics2RouterlessModule' was called.
```

I'm using @angular/cli v 1.7.3.

**Comment by gdlm91** [comment]
I'm trying to use it this way:

```javascript
// app.module.ts
import { Angulartics2RouterlessModule } from 'angulartics2/routerlessmodule';

@NgModule({
    imports: [ Angulartics2RouterlessModule.forRoot([Angulartics2Segment]) ]
    ...
})
```

**Comment by Kamieniu** [comment]
Update to newest version of TS did the work ;)

**Comment by njoanc** [comment]
I got this error! How can I fix it ? ERROR in src/app/goal.ts(1,22): error TS2307: Cannot find module '../../goals'.

I am trying to use this:
import { Goal } from '../../goals';
export var Goals: Goal[] = [
	new Goal(1, 'Watch Finding Nemo', 'Find an online version and watch merlin find his son', new Date(2018, 3, 14)),
	new Goal(2, 'Buy Cookies', 'I have to buy cookies for the parrot', new Date(2018, 6, 9)),
	new Goal(3, 'Get new Phone Case', 'Diana has her birthday coming up soon', new Date(2018, 1, 12)),
	new Goal(4, 'Get Dog Food', 'Pupper likes expensive sancks', new Date(2018, 0, 18)),
	new Goal(5, 'Solve math homework', 'Damn Math', new Date(2018, 2, 14)),
	new Goal(6, 'Plot my world domination plan', 'Cause I am an evil overlord', new Date(2018, 3, 14))
];

 and 
import { Component, OnInit } from '@angular/core';
import { Goals } from '../goal';
@Component({
	selector: 'app-goal',
	templateUrl: './goal.component.html',
	styleUrls: [ './goal.component.css' ]
})
export class GoalComponent implements OnInit {
	goals = Goals;
	constructor() {}

	ngOnInit() {}
}

**Comment by RushiPatel29** [comment]
error TS2307: Cannot find module './_helpers/must-match.validator'.

**Comment by habibulla4455** [comment]
ERROR in src/app/app.module.ts(11,38): error TS2307: Cannot find module './api-keys'.

**Comment by ragegonzales** [comment]
ERROR in src/app/app.module.ts(16,32): error TS2307: Cannot find module 'env/config'.

Help please? How do I know where src/app/app.module.ts?

**Comment by pragathyt95** [comment]
@RushiPatel29 , did u fix that issue? i'm also facing the same now. "Cannot find module './_helpers/must-match.validator'. "

**Comment by yaamoussa** [comment]
'./app/family.component'.
'./app/family.service'.


essai ceci avec moi sa fonctionne:Cannot find module '../services/appareil.service' or its corresponding type declarations.
marche:
'./services/appareil.service';

regarder bien l emplacement par rapport au doccier :app 
meme niveau :./
sous dossier :../
