### ISSUE TITLE
Property 'next' does not exist on type

### ISSUE THREAD

**Issue by pfernandez-growandfit** [angulartics/angulartics2#235]
Hi you there!

I'm working on Angular 5 & Angulartics2.

When trying to create an event through Angulartics2GoogleAnalytics we are finding a problem:

We are building the importing like this:

```
import { Angulartics2Module } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/ga';
```

And the construction like this:

```
  constructor(private angulartics2Module: Angulartics2Module,
              private angulartics2GoogleAnalitics: Angulartics2GoogleAnalytics) {
   }

```
But when we build the function on the same TS file:

```
clickOnIt() {
    this.angulartics2GoogleAnalitics.eventTrack.next({ action: 'Sale', properties: { category: 'Shirt', label: '30' }});
  }
```

We are getting the following error from Eclipse:

> Property 'next' does not exist on type '(action: string, properties: any) => void'.

Please, can you please help with this?

**Comment by mattmeye** [comment]
did
`this.angulartics2GoogleAnalitics.eventTrack('MyAction', {
        category: 'MyCategory',
        label: 'MyLabel',
        value: 'MyValue'
      })`
solve your problem?

**Comment by scttcper** [comment]
Importing the module isn't useful. Import and use `Angulartics2` to do your custom event tracking.

`import { Angulartics2 } from 'angulartics2';`

Angulartics2.eventTrack

**Comment by scttcper** [comment]
or if you like you can use angulartics2GoogleAnalitics and call eventTrack but its a function and not an event emitter.

**Comment by pfernandez-growandfit** [comment]
Thanks @mattmeye , 

It worked for Eclipse but events were not able to arrived to Google Analytics - for some other reason I guess. We have finally opted for Google Tag Manager, but again thank you!
