### ISSUE TITLE
Angulartics broken in ng2.beta.17/rxjs.beta.6

### ISSUE THREAD

**Issue by fergusg** [angulartics/angulartics2#24]
The hot-off-the-press `angular2 2.0.0-beta.17` needs `rxjs 5.0.0-beta.6` but `rxjs/subject/ReplaySubject` seems to have moved to `rxjs/ReplaySubject`.   

I did try hacking the source code, but I made little progress.

**Comment by jamescarter-le** [comment]
I've literally just created a PR for this change: https://github.com/angulartics/angulartics2/pull/23

**Comment by fergusg** [comment]
Ha! I bow to to the superior dev! :-)

**Comment by jamescarter-le** [comment]
Perhaps you can see why the tests are failing, I didnt have time to fully investigate just wanted to try out the lib :smile:

**Comment by fergusg** [comment]
Well, when I tried your suggestion 

```
"angulartics2": "git://github.com/jamescarter-le/angulartics2.git"
```

nothing was installed except a `package.json` and 2 `.md`.

**Comment by jamescarter-le** [comment]
I had to add "files" to package.json for the files to be downloaded, I didnt realise these were ommited from the package.json checked into the master repo here.

Delete the downloaded node_modules/angulartics2 folder and try again.

**Comment by fergusg** [comment]
Not working for me.  There's only an `index.ts` not an `index.js` so my build fails.  Quite poss. an issue with my build setup.

**Comment by jamescarter-le** [comment]
Hmm, I don't get the index.js file but I think that's a build artifact for
the tests.

My compiler just runs through the typescript files.

**Comment by fergusg** [comment]
I though `import` needs a `.js` (I'm not using webpack)

**Comment by jamescarter-le** [comment]
Ah, sorry I can't be of more help :( I am fully typescript in this project.

I just import the lib using its name and the typescript loader in webpack
sorts it all for me...

**Comment by fergusg** [comment]
I'm all typescript too!   But `import {blah} from "angular2/core"` (for example) looks at `core.js`

**Comment by jamescarter-le** [comment]
Maybe the npm package created by the angulartics2 author includes the JS
file your missing?

**Comment by fergusg** [comment]
Indeed.  `"angulartics2": "^1.0.9"` has an `index.js` (no `.ts` except the `.d.ts`)

**Comment by jamescarter-le** [comment]
Ah, sorry I don't know how to package that up for you :(

**Comment by fergusg** [comment]
OK - I'll wait for the PR to be merged. 

This is fun (in the sense of sticking cocktail sticks in ones eyes is fun).  Took me 4hrs to get from b16 to b17 today, mostly 'cos of `typing`s shenanigans.

**Comment by jamescarter-le** [comment]
Sorry, if I could help I would. I'm sure the author will merge shortly.

PS. Dont forget all the # to let changes for b17!

**Comment by fergusg** [comment]
Easy for a Perl nerd like me :)

**Comment by fergusg** [comment]
@jamescarter-le  And if you though the new ngFor syntax changes, take a looksee at angular2.rc0  Ouch!

**Comment by JonnyBGod** [comment]
just looking at it now... Will try to have all fixed as soon as possible
