### ISSUE TITLE
google tag manager has no instructions

### ISSUE THREAD

**Issue by DoryZi** [angulartics/angulartics2#244]
Seem the readme for google tag manager is empty, the docs should explain how to set it up.
Just like it does for google anayltics?

**Comment by scttcper** [comment]
will accept PR's. feel free to add docs. see #213

**Comment by DoryZi** [comment]
I have never used this before, how can I add a PR?

**Comment by scttcper** [comment]
https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
