### ISSUE TITLE
GTM allows injection?

### ISSUE THREAD

**Issue by martinpastore** [angulartics/angulartics2#248]
Hey, i need allow code injection from GTM on my app. That is possible with Angulartics2gtm?

Thanks!

**Comment by scttcper** [comment]
What is code injection from gtm. are there any docs for this?

**Comment by mzrimsek** [comment]
@martinpastore I ran into this issue with an app I am currently working on where I wanted to inject different GTM code based on environment. I wrote a small NPM package to handle it...maybe it will be helpful for you. https://www.npmjs.com/package/insert-analytics-elements
