### ISSUE TITLE
Massive change in bounce rate

### ISSUE THREAD

**Issue by dottodot** [angulartics/angulartics2#249]
I know this isn't exactly a bug report but I've recently changed a Backbone site over to angular with angulartics2 and there has been a massive change in the bounce rate. Previously it was averaging 50% bounce rate, but since the change it's now around 8% which almost seems too good. I'm just worried that something isn't right somewhere and the analytics results are incorrect because of it.

**Comment by scttcper** [comment]
if you're using google analytics download the browser extension and check what its pushing on page load. Also check that you deleted the initial page view tracking from the tracking code?

https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

**Comment by dottodot** [comment]
Thanks for the info. I'm using GTM and had a pageview trigger setup to fire on all events rather than just the Page View event which will be why the figures were so skewed.
