### ISSUE TITLE
choise Angulartics2GoogleAnalytics or Angulartics2Facebook on eventTracker

### ISSUE THREAD

**Issue by enrael** [angulartics/angulartics2#252]
* [ ] bug report  
* [ ] feature request  
* [x] question about the decisions made in the repository
I have a question about how to do an EvenTrack on facebook pixel or on google analytic or both. since according to I understand both use the same api. I want to know if I can decide between which provider to use when I have both implemented.

**Comment by sandro-csimas** [comment]
Same problem here.
I need to call pageTrack to Google Analytics and eventTrack ("Page View") to Facebook.
The problem is that the second event will be trigger for both Analytics and Facebook.
I thought to call the providers directly but this will skip the logic in Angulartics2 main class.
