### ISSUE TITLE
rxjs6 compat - Cannot find module 'rxjs/interfaces'.

### ISSUE THREAD

**Issue by leo6104** [angulartics/angulartics2#254]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**
 bug report  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
In rxjs 6.0.0-beta and rxjs-compat 6.0.0-beta, we could not import 'rxjs/interfaces'

* **What is the expected behavior?**
Please make v6 branch for angular 6 & rxjs 6 

* **What is the motivation / use case for changing the behavior?**
upgrade to rxjs 6 & install rxjs-compat & ng serve

https://github.com/angulartics/angulartics2/blob/877c4b4d8953dc7f8a614bdb64802b8e1fb84350/src/lib/core/angulartics2.ts#L4

* **Environment:**

please run the following and copy the output
```sh
Angular: 6.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cdk: 6.0.0-beta.5
@angular/cli: 6.0.0-beta.5
@angular/material: 6.0.0-beta.5
@angular-devkit/build-optimizer: 0.4.5
@angular-devkit/core: 0.4.5
@angular-devkit/schematics: 0.4.5
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.5
@schematics/angular: 0.4.5
@schematics/package-update: 0.4.5
typescript: 2.7.2
webpack-cli: 2.0.13
webpack: 4.0.1
```

**Comment by sconix** [comment]
This was fixed with the rxjs beta.1 release, the compat library now provides interfaces as well. Naturally it would be also nice to get version of this that does not require the compat library, but I guess it will anyway take some time that all libraries start to using rxjs 6.

**Comment by leo6104** [comment]
Thanks @sconix I hope that moment come soon. 👍
