### ISSUE TITLE
Hubspot tracking script throws error (possibly RxJs)

### ISSUE THREAD

**Issue by byblix** [angulartics/angulartics2#257]
**I'm submitting a ...**

* [x] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **What is the expected behavior?**
Hubspot tracks the event once, and doesn't fire an error sometimes, from the <script> in the index html. 

* **What is the motivation / use case for changing the behavior?**
I need to implement Hubspot tracking in my Angular 5 app. The issues are: 
1) The tracking seems to happen twice. This is how i do it in the router:
`
this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.hsAnalytics.pageTrack(event.urlAfterRedirects)
      }
    });
  }
`

2) An error occurs in a RxJs lib called "Immediate.js" (this is the main issue).
- It doesn't happen everytime, therefore i suspect synchronous error.
- It only happens, if you click and open a link to my app (fx. app.myapp.com).
- It only happens, when the script is implemented in index.html (the ID is replaced in the real app code):

`<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/{HUBSPOT-ID}.js"></script>
`

Error:

`
Uncaught TypeError: Cannot read property 'bind' of undefined
    at new ImmediateDefinition (Immediate.js:11)
`
Which is this file: @reactivex/rxjs/dist/esm2015/util/Immediate.js

* **Environment:**

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 9.2.0
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.4
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.8.1
webpack: 3.11.0
```

**Comment by scttcper** [comment]
should happen once in v7 with startTracking
