### ISSUE TITLE
Hello, I am trying to create angulartics2 plugin for ELK stack(elasticsearch) for web analytics. I am confused how to start. Is there any documentation or idea to create plugin?

### ISSUE THREAD

**Issue by kailashthakuri** [angulartics/angulartics2#260]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [ ] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Environment:**

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```

**Comment by brunano21** [comment]
👍 

I have the same question, but regarding Splunk.

Any getting started docs for new providers?

**Comment by scttcper** [comment]
Copy and paste another provider and start there.
