### ISSUE TITLE
rxjs v6.0 support

### ISSUE THREAD

**Issue by greg-larson** [angulartics/angulartics2#263]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [ ] bug report  
* [X ] feature request  
* [ ] question about the decisions made in the repository

Is there a beta available that suports Angular v6 / rxjs v6?
What is the expected date to support rxjs v6?

Thanks

**Comment by trycoverio** [comment]
#262

**Comment by scttcper** [comment]
released in a convenient angulartics2 v6
