### ISSUE TITLE
rxjs has no exported member...

### ISSUE THREAD

**Issue by AmirGilboa** [angulartics/angulartics2#268]
ng-cli: 1.6.6
angular: 5.2.2
rxjs: 5.5.6

after installing angulartics2, i get this:
```
 ERROR in node_modules/angulartics2/angulartics2-core.d.ts(1,10): 
 error TS2305: Module '"D:/Projects/xxx/node_modules/rxjs/Rx"' has no exported member 'MonoTypeOperatorFunction'.
```

any idea?

**Comment by scttcper** [comment]
You didn’t say what version but the latest version requires rxjs6

**Comment by belobrad** [comment]
Had the same issue -- going back to angulartics2@5.4.0 solved it for me
