### ISSUE TITLE
Property 'developerMode' does not exist on type 'Angulartics2'

### ISSUE THREAD

**Issue by deepakgonda** [angulartics/angulartics2#270]
**I'm submitting a ...**

* [x] bug report  
* [x] feature request  
* [x] question about the decisions made in the repository

* **What is the expected behavior?**
    Previously we can use `angulartics2.developerMode(true);` to stop tracking in development environment

* **Output of ng --version**
    Angular CLI: 6.0.1
Node: 8.11.1
OS: linux x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

    Package                           Version
-----------------------------------------------------------
    @angular-devkit/architect         0.6.1
    @angular-devkit/build-angular     0.6.1
    @angular-devkit/build-optimizer   0.6.1
    @angular-devkit/core              0.6.1
    @angular-devkit/schematics        0.6.1
    @angular/cli                      6.0.1
    @ngtools/webpack                  6.0.1
    @schematics/angular               0.6.1
    @schematics/update                0.6.1
    rxjs                              6.1.0
    typescript                        2.7.2
    webpack                           4.6.0

* **Here is code snippet**
```import {Component, OnInit} from "@angular/core";
import { Router} from "@angular/router";
import {routerAnimations} from "./animations";
import {Angulartics2GoogleAnalytics} from "angulartics2/ga";
import {environment as env} from "../environments/environment";
import {Angulartics2} from "angulartics2";

@Component({
  selector: "body",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
  providers: [AppserviceService],
  animations: [routerAnimations]
})
export class AppComponent implements OnInit {
 
  constructor(
              private router: Router,
              private location: Location,
              private angulartics2: Angulartics2,
              private angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {

    if (!env.production) {
      angulartics2.developerMode(true);
    }

    router.events.subscribe(event => {});
  }

  ngOnInit() {
   // ... some code here.....
  }
}
```

**Comment by scttcper** [comment]
use settings passed in `Angulartics2Module.forRoot` or import angulartics2 and set `angulartics2.settings.developerMode = true`

**Comment by enniob** [comment]
@scttcper do you know if there are any issue with the developerMode flag? I have it setup on my app.modules.ts to true but I can still see the pages from my development when I login to google Analytics.
