### ISSUE TITLE
Google Tag Manager is not `gtag.js`

### ISSUE THREAD

**Issue by corg** [angulartics/angulartics2#272]
**I'm submitting a ...**

* [x] bug report  

**What is the expected behavior?**

Mentions of `gtag.js` should be removed from documentation/pages that describe `Angulartics2GoogleTagManager` (Google Tag Manager provider).

**What is the motivation / use case for changing the behavior?**

`gtag.js` ([global site tag](https://developers.google.com/analytics/devguides/collection/gtagjs/)) is used to send event data to Google Analytics, AdWords, and Doubleclick. New Google Analytics accounts provide code snippet that uses `gtag` instead of `ga`, making it the recommended way of sending tracking data for that account.

However, source code for `Angulartics2GoogleTagManager` ([src/lib/providers/gtm/gtm.ts](https://github.com/angulartics/angulartics2/blob/master/src/lib/providers/gtm/gtm.ts)) has no mention or usage of `gtag`, nothing that looks like [pageview tracking](https://developers.google.com/analytics/devguides/collection/gtagjs/pages), [event tracking](https://developers.google.com/analytics/devguides/collection/gtagjs/events) or [custom dimensions/metrics setup](https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets) from `gtag.js` documentation. Instead, `Angulartics2GoogleTagManager` uses `dataLayer` manipulation, which is exactly what Google Tag Manager uses ([doc](https://developers.google.com/tag-manager/devguide#events)).

That is why I think that having `gtag.js` mentioned with Google Tag Manager is misleading. While they are similar (see [Google support article](https://support.google.com/tagmanager/answer/7582054?hl=en)), `Angulartics2GoogleTagManager` doesn't provide capabilities of `gtag.js` listed in [documentation](https://developers.google.com/analytics/devguides/collection/gtagjs/) or even uses its JS API.

**Other information**

Issues such as https://github.com/angulartics/angulartics2/issues/155 also suggest that `Angulartics2GoogleTagManager` cannot be used as a provider for `gtag.js`.

**Comment by gbarrionuevo** [comment]
so there's no way to use gtag.js with angulartics at the moment? should i move to google tag managear instead? @corg

**Comment by corg** [comment]
@gbarrionuevo

> so there's no way to use gtag.js with angulartics at the moment?

That's correct, `Angulartics2GoogleTagManager` doesn't use `gtag.js` code.

> should i move to google tag managear instead?

I cannot tell you what to do, but if Google Tag Manager works with your website or app and collects all the data you need for your analytics/measurement purposes — then sure, why not.

**Comment by pankhuri** [comment]
Does that mean we cannot use angularytics2 if we have gtag.js snippet in our GA account?
