### ISSUE TITLE
SetUserProperties not doing anything

### ISSUE THREAD

**Issue by hassanasad** [angulartics/angulartics2#273]
**I'm submitting a ...**

* [ ] bug report  
* [ ] feature request  
* [ X ] question about the decisions made in the repository

I am trying to set custom properties for GA. This is my code and is console it prints out correctly. However i dont see this data in Analytics account. I do get the correct active users though. Any suggestions?

```
const properties = {
	userId    : this.userService.getUserId(),
	userName  : this.userService.getUserFullName(),
};
this.angulartics2GoogleAnalytics.setUserProperties( properties );
```

**Comment by gchovanyecz** [comment]
I had the same problem...

**Comment by hassanasad** [comment]
@gchovanyecz Were you able to resolve it ? I had to comment out the code because it was doing nothing.

**Comment by gchovanyecz** [comment]
@hassanasad I try to use setUserProperties in my app.component constructor, but it looks like does nothing. Mybe I put window.ga('set', 'userId', <USER_ID>) into this section.

**Comment by enniob** [comment]
I'm trying to add the userId to my website and I'm getting the same issue.

Has anyone solved this?

**Comment by zaiddabaeen** [comment]
I am using google analytics object directly rather than using angulartics for this. Beats the purpose but seems to work fine ¯\_(ツ)_/¯.

**Comment by jmichaud-ips** [comment]
If I use Angulartics2 ( import { Angulartics2 } from "angulartics2";) then I can do Angulartics2.setUserProperties.next({"dimension1": value});. However, if I do that twice, then I only get the last custom dimension sent. I'm using the uirouter module and google analytics.

**Comment by gwenaellarmet** [comment]
Hello, has anyone succeeded to put some UserProperties with angulartics2 ? 
For me : 

- `Angulartics2.setUserProperties.next({dimension1: value, dimension2: value});` return `Angulartics2.setUserProperties.next is not defined`

-  `Angulartics2.setUserProperties({dimension1: value, dimension2: value});` doesn't throw any error however I can't find my userProperties back in `analytics.google.com`

- `window.ga('set', 'dimension1', value)` doesn't do anything

**Comment by lgoudriaan** [comment]
Nope, it doesn't work for me either

**Comment by jessemorton** [comment]
Using `ga` directly works, but I also didn't find a way to do it through angulartics2. Here's what's working for me accessing `ga`:

`(<any>window).ga('set', 'metric1', 1);`

Note that you need to have set this up for your analytics account already, as described at https://support.google.com/analytics/answer/2709829?hl=en&ref_topic=2709827

**Comment by fhewitt** [comment]
You can't pass through Angulartic2 for that. The `setDimensionsAndMetrics` method and everything around this feature is not implemented inside the gst provider. Not a surprise that this thing does nothing...

I have an outdated version of a custom GST provider, I will propose a PR.

**Comment by DanielCaspers** [comment]
> Using `ga` directly works, but I also didn't find a way to do it through angulartics2. Here's what's working for me accessing `ga`:
> 
> `(<any>window).ga('set', 'metric1', 1);`
> 
> Note that it only sets/merges the metric upon the next GA hit, such as a pageview or event. There's no immediate query to GA just from doing the `set` above.
> 
> Note that you need to have set this up for your analytics account already, as described at https://support.google.com/analytics/answer/2709829?hl=en&ref_topic=2709827

Also keep in mind that depending on if you are building for production or with AoT, you may need to inject window to get this to work

**Comment by Bizotics-Dev** [comment]
Still setUserProperties not works for dimensions.Any new update for how we send additional data using angulartics2 ?
