### ISSUE TITLE
angulartics2 rxjs/ng version compatibility

### ISSUE THREAD

**Issue by arawinters** [angulartics/angulartics2#275]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [x] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
npm install angulartics2 --save
npm install rxjs@^5.5.11
npm start
```

after installing and running webpack throws a:
**ERROR in node_modules/angulartics2/angulartics2-core.d.ts(1,10): error TS2305: Module '"C:/Users/arawi/www/path/to/node_modules/rxjs/Rx"' has no exported member 'MonoTypeOperatorFunction'.**

I'm assuming this is some sort of "they changed something in version x.x.x of rxjs" or ng5 thing. Tried bumping up to ^6.0.0. which basically caused the whole app to go cross-eyed. I could probably justify upgrading ng and rxjs, but that's going to add a huge amount of development time. Any suggestions? what versions of rxjs/angular are you guys running tests against? 

* **What is the expected behavior?**
it compiles.

* **What is the motivation / use case for changing the behavior?**

* **Environment:**
  "dependencies": {
    "@ angular/animations": "^5.2.0",
    "@ angular/cdk": "^5.2.1",
    "@ angular/common": "^5.2.0",
    "@ angular/compiler": "^5.2.0",
    "@ angular/core": "^5.2.0",
    "@ angular/forms": "^5.2.0",
    "@ angular/material": "^5.2.1",
    "@ angular/platform-browser": "^5.2.0",
    "@ angular/platform-browser-dynamic": "^5.2.0",
    "@ angular/router": "^5.2.0",
    "@ ngrx/effects": "^5.0.0",
    "@ ngrx/store": "^5.0.0",
    "@ ngrx/store-devtools": "^5.0.0",
    "angulartics2": "^6.1.0",
    "core-js": "^2.4.1",
    "d3": "^4.10.2",
    "file-saver": "1.3.3",
    "hammerjs": "^2.0.8",
    "numeral": "^2.0.6",
    "rxjs": "^5.5.11",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@ angular/cli": "1.6.6",
    "@ angular/compiler-cli": "^5.2.0",
    "@ angular/language-service": "^5.2.0",
    "@ types/jasmine": "~2.8.3",
    "@ types/node": "~8.0.45",
    "codelyzer": "~4.0.1",
    "faker": "^4.1.0",
    "gulp": "^3.9.1",
    "gulp-sass": "^3.1.0",
    "gulp-string-replace": "^0.4.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "node-sass": "^4.5.3",
    "protractor": "~5.2.0",
    "rollup": "^0.42.0",
    "sass-loader": "^6.0.5",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.0"
  }

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```

Angular CLI: 1.6.6
Node: 8.10.0
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@ angular/cdk: 5.2.5
@ angular/cli: 1.6.6
@ angular/material: 5.2.5
@ angular-devkit/build-optimizer: 0.0.42
@ angular-devkit/core: 0.0.29
@ angular-devkit/schematics: 0.0.52
@ ngtools/json-schema: 1.1.0
@ ngtools/webpack: 1.9.6
@ schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0

**Comment by scttcper** [comment]
angulartics v5.4.0 was last to support rxjs v5.5

**Comment by arawinters** [comment]
thanks. that works enough for me to do the pre-implementation discovery.
