### ISSUE TITLE
Readme.md incorrect instructions for use.

### ISSUE THREAD

**Issue by mohc** [angulartics/angulartics2#277]
Version 5.4

The main readme.md and the ga / gtm sub-module readme.md provide instructions to include the module with the wrong path:
```
import { Angulartics2Module } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/ga';
import {Angulartics2GoogleTagManager} from 'angulartics2/gtm;
```
This results in compilation error:
```
ERROR in src/app/app.module.ts(36,44): error TS2307: Cannot find module 'angulartics2/gtm'.
```

**Comment by scttcper** [comment]
The paths in the docs are correct

**Comment by mohc** [comment]
v5.3 compiles with the paths:
``` 
import {Angulartics2GoogleTagManager} from 'angulartics2/gtm;
```

v5.4 fails compilation

ERROR in src/app/app.component.ts(4,44): error TS2307: Cannot find module 'angulartics2/gtm'.
src/app/app.module.ts(36,44): error TS2307: Cannot find module 'angulartics2/gtm'.

Changing the paths to .../gtm/gtm corrects the problem in my PHPStorm IDE, however it does not correct the compilation error, so sorry that was misleading.

**Comment by aershov24** [comment]
Same for ga:
import { Angulartics2GoogleAnalytics } from 'angulartics2/ga/ga';
