### ISSUE TITLE
Add a method in the Google Analytics Provider to explicitly start tracking route changes

### ISSUE THREAD

**Issue by rossedfort** [angulartics/angulartics2#282]
**I'm submitting a ...**

* [ ] bug report  
* [x] feature request  
* [x] question about the decisions made in the repository

---

Under step 2 of **Include it in your application** in the [angulartics documentation](https://github.com/angulartics/angulartics2#include-it-in-your-application), It says simply injecting the `Angulartics2GoogleAnalytics` provider in your root application component will start tracking route changes. This is true, it works fine, however, the approach goes against some general conventions. The documentation implies to inject the provider into the component, but forgo making it a member of any instances of the component class (implied by lack of `private` or `public` keyword in the constructor). This seems right, however, the value of the provider is never used in the constructor.  This causes the TypeScript compiler to complain, if you have the following rule enabled:

tsconfig.json
```json
"noUnusedLocals": true
```
```typescript
export class AppComponent {
  constructor(angulartics: Angulartics2GoogleAnalytics) {} // not good, angulartics is never used in the constructor
}
```
---
Adding the `public` keyword to the injection, thus making the provider a public member on the instance of the component gets ride of the compiler error (because the compiler can't check if its value is ever used), but makes the code incorrect.
```typescript
export class AppComponent {
  constructor(public angulartics: Angulartics2GoogleAnalytics) {} // not good, this.angulartics is not accessed by any other classes 
}
```
---
Adding the `private` keyword to the injection, thus making the provider a private member on the instance of the component seems more correct, yet again, causes a compiler error, as its value is never used
```typescript
export class AppComponent {
  constructor(private angulartics: Angulartics2GoogleAnalytics) {} // not good, this.angulartics is not accessed within this class
}
```
---
My suggestion/request is to implement a method that users would call to explicitly initiate tracking. This ensures the code is conventional.
```typescript
export class AppComponent {
  constructor(angulartics: Angulartics2GoogleAnalytics) {
    angulartics.startRouteTracking(); // good, angulartics is not a member on the instance, and its value is used in the constructor
  }
}
```
Unless I'm missing something, [TSLint](https://palantir.github.io/tslint/rules/no-unused-variable/), the [TypeScript compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html), and even [Angular's Dependency Injection Documentation](https://angular.io/guide/dependency-injection#inject-a-service) all indicate this as a code smell. 

Thanks for reading, and thanks for this great library.

```
$ ./node_modules/.bin/ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 9.0.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.3
webpack: 3.11.0
```

Using angulartics [5.4.0](https://github.com/angulartics/angulartics2/releases/tag/v5.4.0)

**Comment by scttcper** [comment]
i agree. I'd like to see a `start/go/enable()` function of some kind on each of them.

**Comment by rossedfort** [comment]
@scttcper could I take a stab at implementing it for the Google Analytics provider? Or would you prefer they be done all at once?

**Comment by scttcper** [comment]
can just do one if you want, but i wouldn't put it in master until all of them and the docs show how to use it

**Comment by rossedfort** [comment]
I've created PR #283 for this Issue, could a maintainer please take a look?

**Comment by scttcper** [comment]
hey i'm waiting to hear back from one of the other maintainers about updating our npm token thats blocking us from publishing right now. i don't have rights i'd like to add another breaking change or to as well before getting into master.

going to start up the "next" branch again and merge this in.
