### ISSUE TITLE
Tracking not working even when developerMode set to false

### ISSUE THREAD

**Issue by mcblum** [angulartics/angulartics2#289]
**I'm submitting a ...**

* [ x ] bug report  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I'm just getting started with the package and have the following config:
```
Angulartics2Module.forRoot([
            Angulartics2Mixpanel
        ], {
            developerMode: false
        })
```
and I have the same provider injected into the root component. Everything is bootstrapping fine and if I just manually dispatch an event to Mixpanel, it works. We have separate Mixpanel apps for each environment, so we do actually want to report analytics for dev, test, stage, and prod.

* **What is the expected behavior?**
Setting `developerMode` to `false` would allow events through.

* **What is the motivation / use case for changing the behavior?**
Testing and analytics in lower environments.

* **Environment:**

please run the following and copy the output
```
Angular CLI: 6.0.1
Node: 9.11.1
OS: darwin x64
Angular: 6.0.1
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.1
@angular/animations                6.0.4
@angular/cdk                       6.2.1
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.1
@schematics/update                 0.6.1
ng-packagr                         3.0.1
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.8.3

```

**Comment by scttcper** [comment]
tracking was previously started by calling the constructor of your provider in your root app component. In v7 it forces users to start tracking manually.
