### ISSUE TITLE
Support disabling pageview tracking completely

### ISSUE THREAD

**Issue by mgol** [angulartics/angulartics2#293]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [ ] bug report  
* [x] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

I'd like to be able to disable page view tracking completely.

* **What is the motivation / use case for changing the behavior?**

Sometimes the built-in tracking is not enough. In one of my apps I first need to wait for the Angular's [Meta service](https://angular.io/api/platform-browser/Meta) to set meta tags based on data from the backend and only then track the page.

I hacked the settings around by setting [`excludedRoutes`](https://github.com/angulartics/angulartics2#exclude-routes-from-automatic-pageview-tracking) to an empty string but this seems more like a hack than a true solution and I'm afraid it might break in the future.

* **Environment:**

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```
Output:
```
Angular CLI: 6.1.1
Node: 8.11.3
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cdk                      6.4.1
@angular/cli                      6.1.1
@angular/material                 6.4.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.2
```

**Comment by llwt** [comment]
It looks like it does already.

From the Readme:

> Using Without A Router
Warning: this support is still experiemental
@angular/router must still be installed! However, it will not be used.
```
import { Angulartics2RouterlessModule } from 'angulartics2/routerlessmodule';
@NgModule({
  // ...
  imports: [
    BrowserModule,
    Angulartics2RouterlessModule.forRoot([Angulartics2GoogleAnalytics]),
  ],
})
```

**Comment by scttcper** [comment]
There's now even more options for this in the readme.

**Comment by mgol** [comment]
OK, thanks!
