### ISSUE TITLE
Google Tag Manager still doesn't appear to use gtag()

### ISSUE THREAD

**Issue by mcblum** [angulartics/angulartics2#295]
**I'm submitting a ...**

* [x] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Hi - I'm using Google Tag Manager and the gtag code in order to track page views and events. For whatever reason, the provider doesn't use `gtag()` but rather `ga()` to send events, which fails. If I do the following manually it succeeds:

```
   gtag('event', 'test', {
            event_category: 'Videos',
            event_label: 'Fall Campaign'
        });
```

It looks like new code was merged to address this in 6.3.0, but I have that version and it still doesn't seem to work.

* **What is the expected behavior?**

That GoogleTagManager would use `gtag()` to send events.

* **What is the motivation / use case for changing the behavior?**

* **Environment:**

```
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/animations                6.0.3
@angular/cdk                       6.4.1
@angular/material                  6.4.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.1
ng-packagr                         3.0.3
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.8.3
```

**Comment by scttcper** [comment]
https://github.com/angulartics/angulartics2/blob/master/src/lib/providers/gtm/gtm.ts

gtm is most likely the provider you're looking for since gtag uses datalayer underneath.
