### ISSUE TITLE
"Page Viewed" is being tracked even custom event are fired

### ISSUE THREAD

**Issue by mrugank84** [angulartics/angulartics2#302]
Hello 

I implement angulartics2 version 3.6.0 in my Angular 5 application.

in my module id added provider as below.

` imports: [ Angulartics2Module.forRoot([Angulartics2Mixpanel]) ]`

Now in component i passed Angulartics2Mixpanel in constructor of component as below and called eventTrack method to pass custom event name.

```
constructor(private mixPanel: Angulartics2Mixpanel) {}

ngOninti()
{
this.mixPanel.eventTrack("pageview", { "event": event, "userId": loggedinUser.email });
}

```
Even by doing above some other events are keeping on firing when route changes and it is track as "Page Viewed"

How to stop doing this? is this bug?

**Comment by scttcper** [comment]
```ts
// this calls the mixpanel class constructor
constructor(private mixPanel: Angulartics2Mixpanel) {}
```

in angulartics 3.6.0. Calling any of the constructors automatically started event and route tracking.

**Comment by mrugank84** [comment]
> mixPanel

How to stop it? As without injecting it in constructor of  component we wan't be able to call in component

`this.mixPanel.eventTrack("pageview", { "event": event, "userId": loggedinUser.email });`

**Comment by scttcper** [comment]
Update the version of anagulartics you are using.
