### ISSUE TITLE
Is it a good idea to use provideIn: root for the main service?

### ISSUE THREAD

**Issue by asgerjensen** [angulartics/angulartics2#306]
In our shared library, we have angulartics2 as an optional dependency. Meaning, if the consumer of the shared library installs angulartics2, and decides to provide the Angulartics2Module in their app.module, we will emit events on that channel, by doing

```
constructor(@Optional() private angulartics: Angulartics2)
```

But after it was switched to use `provideIn: root`, I get DI errors that Routerless is not provided, in projects that dont want to use angulartics. It also means all unittests needs to provide both Angulartics2Module and RouterTestingModule if they happen to use the class above.

Before, if I didnt provide `Angulartics2Module` in `app.module`, the @Optional() dependency would return null. Now, it will try to instantiate the service, regardless of whether or not the module is installed. And will fail, since it depends on other internal services of angulartics2, that has not been instantiated.

As angulartics2 is a utility library outside the consumers control, I feel it should be the consumers choice to add the module or not.

```
                                                                          MySharedLib
 
                                  MyFrontEnd (MySharedLib)          MyOtherFrontend(MySharedLib + Angulartics2)

```

**Comment by scttcper** [comment]
Totally honest here, if you have enough angular projects to require a shared library. You might consider rolling your own analytics, since at most there's a router subscription and a small wrapper around your analytics provider. I'll think more about this though.
