### ISSUE TITLE
Compile error of cannot find module rxjs/interfaces

### ISSUE THREAD

**Issue by Ranhuo** [angulartics/angulartics2#309]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [ ] bug report  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

On the root module, I follow instructions. 
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    Ng2DeviceDetectorModule.forRoot(),
    BrowserAnimationsModule,
    ToastModule.forRoot(),
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    MaterialModule,
    HttpModule,
    SharedModule,
    MerchantPagesModule,
    TmpModule,
    ConsumerPagesModule,
    FeaturesModule,
    OverlayModule,
    CoreModule,
    Angulartics2Module.forRoot([Angulartics2GoogleAnalytics]),
  ],
```
Saved the changes and got compile error of "Cannot find module 'rxjs/interfaces'. "
* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Environment:**

please run the following and copy the output
```sh
@angular/cli: 1.4.2
node: 8.11.4
os: darwin x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.10
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.3
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/platform-server: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.2
@angular/common: 4.4.4
@angular/core: 4.4.4
typescript: 2.3.2
```

**Comment by scttcper** [comment]
update your dependencies and follow the latest instructions.
