### ISSUE TITLE
Documentation on gtag doesn't work

### ISSUE THREAD

**Issue by ojemuyiwa** [angulartics/angulartics2#317]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a bug / query**

* [ ] bug report  

* **
Go to https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/gtm
follow steps on app.module 
Type script error: [ts] Type '(typeof Angulartics2GoogleTagManager)[]' has no properties in common with type 'Partial<Angulartics2Settings>'. [2559]
**

* **What is the expected behavior?**
Your code should work as documented

* **What is the motivation / use case for changing the behavior?**
So we don't have to guess and hack the planet in order to install

* **Environment:**
MacOS

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```
Angular CLI: 7.0.6
Node: 8.10.0
OS: darwin x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@angular/pwa                      0.10.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

**Comment by Firtzberg** [comment]
The documentation isn't aligned since this merge https://github.com/angulartics/angulartics2/pull/284/
In src/lib/core/angulartics2.module.ts the providers were replaced by hardcoded 'Angulartics2'. I think it should be possible to replace it with Angulartics2GoogleTagManager

**Comment by ojemuyiwa** [comment]
Thanks.

**Comment by scttcper** [comment]
the types are correct. you do not pass providers to Angulartics2Module.
