### ISSUE TITLE
@angular/router 3.0.0 support?

### ISSUE THREAD

**Issue by briananderson1222** [angulartics/angulartics2#32]
I am having a hell of a time trying to figure out where I am going wrong..

// main.ts
import {Angulartics2} from 'angulartics2';

bootstrap(AppComponent, [
ROUTER_PROVIDERS, HTTP_PROVIDERS, TRANSLATE_PROVIDERS,
provide(LocationStrategy, {useClass: HashLocationStrategy}), Angulartics2
]).catch(err => console.error(err));

// app.component.ts
import {Angulartics2GoogleAnalytics} from 'angulartics2/src/providers/angulartics2-google-analytics';

@Component({
  moduleId: module.id,
  selector: 'app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [ROUTER_DIRECTIVES],
  pipes: [TranslatePipe],
  providers: [Angulartics2GoogleAnalytics]
})

// index.html
  ga('create', 'TRACKING_ID_HERE', 'auto');

All of the files are getting loaded appropriately (I can see them loaded within the 'Sources' tab in chrome) but I can't hit any breakpoints within any of these files and no page views are getting tracked (I don't see any requests in the browser or within google analytics)..  Am I missing something or is this just not operational with the new angular 2 router? Please let me know if there is any more information I can provide.

**EDIT: Make sure you actually inject the components in your AppComponent..**

**Comment by NathanWalker** [comment]
Right now, auto page tracking only works for the first load, but subsequent route changes are not working with the new router.

For now you can use the extended class posted[here](https://github.com/angulartics/angulartics2/issues/29#issuecomment-220213585) as a workaround.
We hope this is addressed in angular builds over next couple weeks.

**Comment by briananderson1222** [comment]
This work around injects the deprecated router. I tried updating it and
using the new router by using router.changes.subscribe (not sure this is
correct) but even without any of these changes I'm unable to even get the
initial page load to be tracked which makes me think I am missing something
obvious. I'll continue trying to get it working later this evening but if
anyone has any ideas I'm all ears..

Thanks for the quick response.

**Comment by NathanWalker** [comment]
I believe the *new* router is not firing changes on route changes (maybe even the first load).... the deprecated router is still more stable/predictable at moment but that will change soon.

**Comment by briananderson1222** [comment]
@NathanWalker Didn't know if it was worth opening another issue, but just thought i'd repurpose this one to refer to the new @angular/router 3.0.0 router. For reference: http://angularjs.blogspot.mx/2016/06/improvements-coming-for-routing-in.html . If I get a chance I can try to dig in and put up a PR but just wanted to have this issue referencing that.

**Comment by briananderson1222** [comment]
This plugin is dependent on the Location service.. not router

**Comment by MJLang** [comment]
Issue is, the new router doesnt trigger a location update event.

**Comment by hem19** [comment]
@MJLang I am using Angular RC.4 and Router 3.0.0-beta.1, I don't see any **router.events.filter** function. So I am trying to write the logic as suggested here http://stackoverflow.com/a/38080657/5396181

```
constructor(router:Router) {
  router.events.subscribe((event:Event) => {
    if(event instanceof NavigationStart) {
    }
    // NavigationEnd
    // NavigationCancel
    // NavigationError
    // RoutesRecognized
  }
}
```

It is giving the error that type 'NavigationStart | NavigationEnd | NavigationCancel | NavigationError' is not assignable to type 'Event'

Is this functionality changed in RC.4?

**Comment by Amitgr8** [comment]
@hem19  import {ActivatedRoute , Router ,NavigationEnd} from '@angular/router';  write this import and it may solve the issue
