### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by ktwbc** [angulartics/angulartics2#327]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [X ] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I'm unable to get this package working after a deploy. When running ng serve and testing locally, everything works perfectly. Once it's built with ng build and deployed, launching the page fails immediately with $ is not defined
I'm using the Google tag Manager function.

output below (GTM code masked)
```
VM110:1 Uncaught ReferenceError: $ is not defined
    at <anonymous>:1:199
    at <anonymous>:1:365
    at gtm.js?id=GTM-XXXXXX:984
    at Object.c [as __html] (gtm.js?id=GTM-XXXXXX:986)
    at Uc (gtm.js?id=GTM-XXXXXX:873)
    at h (gtm.js?id=GTM-XXXXXX:890)
    at gtm.js?id=GTM-XXXXXX:813
    at Array.<anonymous> (gtm.js?id=GTM-XXXXXX:891)
    at Object.M (gtm.js?id=GTM-XXXXXX:890)
    at ff (gtm.js?id=GTM-XXXXXX:900)
```
* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Environment:**

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.4
Node: 8.12.0
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.0
```

**Comment by fhewitt** [comment]
@ktwbc The issue came from the GoogleTagManager script, not from the Angulartics2 code (which didn't use jQuery or `$`). My first guest is that the gtm settings are incorrect or that you're ad blocker cause issues with gtm dependencies.
