### ISSUE TITLE
Get weird injector error

### ISSUE THREAD

**Issue by vance** [angulartics/angulartics2#333]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [x] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
// from the barrel:
import { Angulartics2 } from 'angulartics2';
export const WEB_ANALYTICS_PROVIDERS: Provider[] = [
  { provide: AnalyticsTrackable, useClass: WebAnalyticsService },
  Angulartics2Google,
  Angulartics2,
];

// provided in core web module:
@NgModule({
  // ...
  providers: [
    ... WEB_ANALYTICS_PROVIDERS,
   ]

Then I get this error at runtime. 

Error: StaticInjectorError(AppModule)[Angulartics2 -> RouterlessTracking]: 
  StaticInjectorError(Platform: core)[Angulartics2 -> RouterlessTracking]: 
    NullInjectorError: No provider for RouterlessTracking!

Maybe I'm missing something simple.

**Comment by mathias-ewald** [comment]
@vance Have you been able to resolve this? I am seeing the same error.

**Comment by dannygoncalves** [comment]
@vance +1 how did you solved this? might be worth adding an explanation about why did you closed it.

**Comment by vkolesnikov-bmt** [comment]
@vance +1 could you describe how you resolved this?

**Comment by kmturley** [comment]
I was getting a similar error when I ran Angular tests using: `ng test`

I solved by updating my app.component.spec.ts to have

```
import { Angulartics2, Angulartics2Module} from 'angulartics2';
...
.configureTestingModule({
  imports: [RouterTestingModule, BrowserAnimationsModule, Angulartics2Module.forRoot()],
  declarations: [AppComponent],
  providers: [Angulartics2],
})
```
