### ISSUE TITLE
ga basic ecommerce tracking

### ISSUE THREAD

**Issue by dodoshanti** [angulartics/angulartics2#34]
Would doing a PR for this be useful and what's the best way to add this in; a new provider or add to the existing one?
Thanks

**Comment by JonnyBGod** [comment]
I am not familiar with the ecommerce and many other tracking types for GA. That said and after a quick read on it, it seam to be about supporting a few extra tracking commands. If that is the case I would say we can just extend the GA provider with these commands and try to support them in the angulartic2On directive.

I am pretty confident that for the GA provider we can just add the new commands as the overhead won't be considerable.

I am not so sure in angulartics2On directive case.

Maybe try a PR extending both for now and we can work on a possible separation later after having a better look of what is involved.
