### ISSUE TITLE
Directive angulartics2O doesn't work with ng2-bootstrap tabs

### ISSUE THREAD

**Issue by stevo-knievo** [angulartics/angulartics2#36]
The events doesn't get fired on the [ng2-bootstrap tab](https://github.com/valor-software/ng2-bootstrap). I tried with angulartics2On="click" as well. No luck.. 

```
<tabset>   
  <tab heading="Category" (select)="onTabSelect($event)" angulartics2On="select" angularticsEvent="ResultTab" angularticsCategory="'Category'">
      ....
  </tab>
  <tab heading="Time" (select)="onTabSelect($event)" angulartics2On="select" angularticsEvent="ResultTab" angularticsCategory="'Time'">
      ....
  </tab>      
</tabset>
```

Our example works fine:

`<div angulartics2On="click" angularticsEvent="DownloadClick" angularticsCategory="{{ song.name }}"></div>`

angular: 2.0.0-rc.1
angulartics2: 1.0.11
ng2-bootstrap: 1.0.16

Thanks, Stefan

**Comment by Hongbo-Miao** [comment]
Same to me,

    <tab heading="Learn"
           angulartics2On
           angularticsCategory="Random"
           angularticsEvent="Select a tab"
           (select)="onSelect()">

See [here](https://github.com/valor-software/ng2-bootstrap/blob/554be3d9b329c2f75c1f4d4a4cfeff43b4723c88/components/tabs/tab.directive.ts#L21), `(select)` is a custom event which belongs to `TabDirective`, I guess `angulartics2On` does not support custom event now.

Also, `TabDirective` does not have `(click)`, so click event also does not applies.

    <tab heading="Learn"
           angulartics2On
           angularticsCategory="Feedback"
           angularticsEvent="Select learn tab"
           (click)="onClick()">

```
onClick() {
  console.log('click');    // will never run
}
```

**Comment by Hongbo-Miao** [comment]
@stevo-knievo hi, check my comment https://github.com/angulartics/angulartics2/issues/42, I feel that is a good way to go.

**Comment by scttcper** [comment]
@Hongbo-Miao is right. The best way to support this would be to fire the event via the service in the function on (click).
