### ISSUE TITLE
Google Tag Manager & angulartics2

### ISSUE THREAD

**Issue by srippey4** [angulartics/angulartics2#39]
Does anyone have working examples for using angulartics2 with Google Tag Manager?

**Comment by cristiandeschamps** [comment]
I don't think the module exist yet.. only GA.

I'm thinking of porting the angulartics1 of gtm module to angulartics2... I really need it for my project.

**Comment by mpetkov** [comment]
Is there a timeline on when Google  Tag Manager will be supported?

**Comment by JonnyBGod** [comment]
I don't have experience with GTM. It is very easy to implement a new provider for angulartics2, PR is welcome.

**Comment by cristiandeschamps** [comment]
I found this link, and because we need to go live really soon I will use this instead, but I'm also looking for angulartics2/gtm, but right now I don't have enough time.. 

http://blog.thecodecampus.de/angular-2-google-analytics-google-tag-manager/

**Comment by kspdrgn** [comment]
Took a stab at a GTM provider, but havn't got it work in my app yet. Maybe someone can see if this helps them: [https://github.com/kspdrgn/angulartics2/tree/gtm](https://github.com/kspdrgn/angulartics2/tree/gtm)

**Comment by jylinman** [comment]
Hey guys, just submitted a PR for GTM with tests.  PR #73

**Comment by JonnyBGod** [comment]
added in [v1.3.0](https://github.com/angulartics/angulartics2/releases/tag/v1.3.0)

**Comment by davidtlee** [comment]
Awesome, thanks @jylinman! Any chance you could update the docs to show a simple example of using angulartics2 with GTM?

**Comment by jylinman** [comment]
Hey @davidtlee NP!  Yeah I wouldn't mind, but I am just wondering if we should probably split up the docs to some sort of readme in the vendors instead?  Seems like a lot of docs if we add all examples in the main README?

**Comment by JonnyBGod** [comment]
@jylinman maybe we could use wiki for docs, one page per provider.

**Comment by JonnyBGod** [comment]
I am attending web summit this week and will be very busy. It would be great if someone could start making wiki based docs.

**Comment by jylinman** [comment]
@JonnyBGod Sounds good to me, if I can get some access to it I can create a page for it...

**Comment by JonnyBGod** [comment]
@jylinman Just added you as a repo collaborator.

**Comment by jylinman** [comment]
Great thanks @JonnyBGod ... I just added the following:

https://github.com/angulartics/angulartics2/wiki

- Homepage
- A sidebar that has hotlinks for different providers / docs
- A tracking events wiki page
- GTM and GA docs

We can link to this from the readme instead of putting the examples there.

**Comment by JonnyBGod** [comment]
Cool great work thanks.

Lets follow this at https://github.com/angulartics/angulartics2/issues/76

**Comment by davidtlee** [comment]
thanks :)
