### ISSUE TITLE
Application Insights provider 

### ISSUE THREAD

**Issue by MedAnd** [angulartics/angulartics2#40]
Hi,

Wondering if there are any plans for an Application Insights provider?

Cheers

**Comment by hikirsch** [comment]
i wrote this it's over here - i'm still testing it

https://github.com/hikirsch/angulartics2

**Comment by JonnyBGod** [comment]
@hikirsch Cool, thanks for the initiative. Let me know when you are ready for a PR. And add yourself to the contributors list.

**Comment by JonnyBGod** [comment]
Landed on [v1.6.0](https://github.com/angulartics/angulartics2/releases/tag/v1.6.0)
