### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by Shereef** [angulartics/angulartics2#402]
**I'm submitting a ...**

* [X ] feature request  

* **What is the expected behavior?**
Support for Angular 12

* **What is the motivation / use case for changing the behavior?**
Being on the latest version and reaping the benefits of the new features and security patches

* **Environment:**
All

please run the following and copy the output
```sh
./node_modules/.bin/ng --version
```

> 
>      _                      _                 ____ _     ___
>     / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>    / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>   / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
>  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                 |___/
> 
> 
> Angular CLI: 10.2.0
> Node: 12.16.3
> OS: win32 x64
> 
> Angular: 10.2.3
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, localize, platform-browser
> ... platform-browser-dynamic, platform-server, router
> Ivy Workspace: Yes
> 
> Package                            Version
> ------------------------------------------------------------
> @angular-devkit/architect          0.1002.0
> @angular-devkit/build-angular      0.1002.0
> @angular-devkit/core               10.2.0
> @angular-devkit/schematics         10.2.0
> @angular/cdk                       10.2.7
> @angular/cli                       10.2.0
> @angular/material                  10.2.7
> @angular/material-moment-adapter   10.2.7
> @schematics/angular                10.2.0
> @schematics/update                 0.1002.0
> rxjs                               6.6.3
> typescript                         4.0.5

**Comment by ebussieres** [comment]
Any plan to upgrade to Angular 11 ?

**Comment by helgetan** [comment]
any updates here?

**Comment by jbjhjm** [comment]
Special: 2 for 1 offer! :O Let's update to Angular 12 :) 
I guess there's nothing to be changed technically, just peer dependency version has to be updated.

**Comment by Shereef** [comment]
Updated the title to Angular 12

**Comment by JonnyBGod** [comment]
@scttcper I just gave you admin access to the repository.

I just checked and apparently travis turn of the .org site and now we have to use the .com. I just requested access to the repository but I do not manage angulartics org so it might take some time.

Maybe it would be best to move to Github actions.

I don't have the time these days to help much but feel free to take it from here.

**Comment by scttcper** [comment]
@JonnyBGod nice! thanks!

Can you add me as a collaborator on the npm package as well? https://docs.npmjs.com/adding-collaborators-to-private-packages-owned-by-a-user-account This way i can setup github actions or another ci with it.

Looks like npm/github is having issues at the moment

**Comment by scttcper** [comment]
@JonnyBGod looks good thanks! should be unblocked from here
