### ISSUE TITLE
No provider error

### ISSUE THREAD

**Issue by dave0783** [angulartics/angulartics2#41]
I am getting: 

`ORIGINAL`` EXCEPTION: No provider for LocationStrategy! (Angulartics2 -> Location -> LocationStrategy)`

Any ideas?

**Comment by dave0783** [comment]
Never mind, I registered it incorrectly.

**Comment by geoHeil** [comment]
After importing `LocationStragegy` I get a T`ypeError: this._platformStrategy.getBaseHref is not a function` error

**Comment by azanebrain** [comment]
I was able to get this working by importing `RouterModule.forRoot([])` into my module. See https://github.com/angulartics/angulartics2/issues/43
