### ISSUE TITLE
Error: No provider for location

### ISSUE THREAD

**Issue by ihadeed** [angulartics/angulartics2#43]
Hey there,

I followed the instructions in your README.md to install this plugin in my Angular 2 application.

I keep getting this error:
```
ORIGINAL EXCEPTION: No provider for Location! (Angulartics2 -> Location)
```

Is it because I'm using `ngrx/router` instead of `angular2/router` ?

**Comment by brandonroberts** [comment]
Yes. You need 

```js
import {Location} from '@angular/common';
````

Add `Location` to your bootstrap array.

**Comment by chaoranxie** [comment]
@brandonroberts  i am also getting this error, i tried to add `Location` to bootstrap array but got the following error `Location cannot be used as an entry component.`. any idea what i did wrong, is there a sample repo i can see how it is setup

`
@NgModule({
  declarations: [    AppComponent  ],
  imports: [
    Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ])
  ],
  providers: [
  ],
  bootstrap: [AppComponent, Location]
})
export class AppModule { }
`

**Comment by brandonroberts** [comment]
You add `Location` to the `providers` array, not the `bootstrap` array

**Comment by chaoranxie** [comment]
i tried that but then i got `No provider for LocationStrategy`

**Comment by brandonroberts** [comment]
What are you trying to do? You shouldn't need to do anything special if you're using this with the Angular router.

**Comment by chaoranxie** [comment]
i guess, i am not using angular router yet,(probably will be soon)  at the moment, this is a simple project with one page. i guess i will just add angular router now.

**Comment by brandonroberts** [comment]
Yea, if you're not using the Angular Router yet then you need to add the Location, and PathLocationStrategy from @angular/common to get those services

**Comment by guilhebl** [comment]
I was getting this error, I added import { RouterModule } from '@angular/router' and it solved the issue, hope it helps.

**Comment by azanebrain** [comment]
For anyone else still hitting this problem but not using routes in your app, make sure to initialize the Router Module correctly and pass an empty array:

```
import { RouterModule } from '@angular/router'

...

@NgModule({
  declarations: [    MyComponent  ],
  imports: [
    Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ]),
    RouterModule.forRoot([])
  ],
  providers: [ ],
})
export class MyModule { }
```

This example is a feature module that uses `forRoot`. I haven't tested it, but I bet that if your App Module is using forRoot, your "MyModule" module will probably need `forChild`

**Comment by omouse** [comment]
@azanebrain perfect answer, wish the docs were updated with this and other examples. it seems like most of the issues being reported are for not enough examples...is it preferable to submit PRs here for that?

**Comment by pleinonen** [comment]
I think dependency on RouterModule is serious limitation for UI-Router users like me.

**Comment by raygerrard** [comment]
I am trying to inject the Location service into a component library that is being used in an app that uses the RouterModule.

I have included the above RouterModule.forRoot([]) but get the following error: NullInjectorError: No provider for PlatformLocation!

**Comment by azanebrain** [comment]
I've run into this before where one of my services using my analytics service gets tripped up by angulartics' requirement for routing/locations. I resolve this by adding a mock service for analytics. If you're using angulartics directly, you can try providing a mocked service, like so:

```
describe('MyTest', () => {
 TestBed.configureTestingModule({
  providers: [
   { provide: Angulartics2GoogleAnalytics, useValue: new AngularticsMock() }
  ]
 })
 ....
})

class AngularticsMock {
  public eventTrack(action, properties) { }
}
```

**Comment by mustafarian** [comment]
I had this issue and wasted sometime debugging it until I realized that my IDE (visual studio code) doesn't detect the missing import for Location. Once I imported location from '@angular/common' the issue went away.

**Comment by sairahul1526** [comment]
@mustafarian could you explain what you did

**Comment by mustafarian** [comment]
@sairahul1526 I just made sure Location is imported from '@angular/common' not the one provided by the browser. I was using "Location" without any import and the IDE didn't show it as an error and the transpilation was completing successfully but when I ran the code in the browser it threw the above error.

**Comment by spustlik** [comment]
Hi, I just have this issue too.
Visual Studio 2017 shows that Location already exists, but as interface Location declared in lib.dom.ts.
So it is ok for transpiler. But when I moved to next item called also "Location", it imported Location from ng/core and everything is ok.
Maybe best thing is to rename it to LocationService, but it is breaking change...
![image](https://user-images.githubusercontent.com/1135561/42266979-1f922ec0-7f78-11e8-919e-a744b9990c7f.png)
![image](https://user-images.githubusercontent.com/1135561/42267016-326fba30-7f78-11e8-8cbd-6bebda83f983.png)

**Comment by eJuke** [comment]
Hi all
For anyone who finds this thread in the future
In case you don't want to import Angular Router, you can just register Location as provider alongside with chosen LocationStrategy
Example: 
```typescript
@NgModule({
  // ..all the declarations you need
  providers: [
    Location,
    { provide: LocationStrategy, useClass: PathLocationStrategy },
  ],
})
export class MyModule { }
```

See [Location service API docs](https://angular.io/api/common/Location#usage-notes) for more details

**Comment by d-loki** [comment]
Thanks @eJuke 

> Hi all
> For anyone who finds this thread in the future
> In case you don't want to import Angular Router, you can just register Location as provider alongside with chosen LocationStrategy
> Example:
> 
> ```ts
> @NgModule({
>   // ..all the declarations you need
>   providers: [
>     Location,
>     { provide: LocationStrategy, useClass: PathLocationStrategy },
>   ],
> })
> export class MyModule { }
> ```
> 
> See [Location service API docs](https://angular.io/api/common/Location#usage-notes) for more details

It's work well, im my case I had to add UrlSerializer and IonicStorageModule

```
TestBed.configureTestingModule( {
                                            imports: [
                                                .......,
                                                IonicStorageModule.forRoot()
                                            ],
                                            providers: [
                                                Location,
                                                { provide: LocationStrategy, useClass: PathLocationStrategy },
                                                UrlSerializer,
                                               ....... ]
                                        } );
    } );
```

**Comment by DaveA-W** [comment]
For others finding this thread in future that _can_ import the Angular Router, you are able to get the requested navigation URL this way:
```
  constructor(private router: Router) {
  }

  canLoad(route: Route, segments: UrlSegment[]) {
    const navigation = this.router.getCurrentNavigation();
    if (navigation) {
      const url = navigation.extractedUrl;
      return this.canUserAccessUrl(url);
    }
    return false;
  }
```
Where `canUserAccessUrl(url: UrlTree)` contains your implementation.
