### ISSUE TITLE
Cordova app

### ISSUE THREAD

**Issue by justme1** [angulartics/angulartics2#47]
Hi,

Any one has any expeirent with Cordova?

After reading the web this line should make it work:

ga('set', 'checkProtocolTask', null);

However, I'm not sure if it actually is working. any one has any experience with this?

**Comment by geoHeil** [comment]
Hi,
you might be interested in https://github.com/angulartics/angulartics2/issues/50 where I try to get it up and running for ionic2 which is based on cordova
