### ISSUE TITLE
How to trigger an event from a component

### ISSUE THREAD

**Issue by hakonamatata** [angulartics/angulartics2#49]
Hi, I have a question

It is explained how to use a directive to attach a event to a button click, but how do I trigger an event in my component. I want to write something like this: 

`this._angulartics2.eventTrack('click', 'DownloadClick', 'song.name');`

But I don't know what the parameters are or how this is supposed to be done??

**Comment by vmironovs** [comment]
import {Angulartics2GoogleAnalytics} from 'angulartics2/src/providers/angulartics2-google-analytics';
use this  and then you can track event 
   this.Angulartics2GoogleAnalytics.eventTrack('Do some action' { category: 'UserClick' });

**Comment by JonnyBGod** [comment]
you can accomplish the same with ```this.angulartics2.eventTrack('ACTION NAME', <PROPERTIES JSON>);

the properties really depends on your data schema or the providers your using.

**Comment by hakonamatata** [comment]
> you can accomplish the same with ```this.angulartics2.eventTrack('ACTION NAME', );
> the properties really depends on your data schema or the providers your using.

This gives me the error: 

**Cannot invoke an expression whose type lacks a call signature**

**Comment by JonnyBGod** [comment]
sorry that was a parsing mistake of course ```this.angulartics2.eventTrack('ACTION NAME', '<PROPERTIES JSON OBJECT>');```
