### ISSUE TITLE
build warnings due to source maps referencing missing source files.

### ISSUE THREAD

**Issue by tbinkleyjones** [angulartics/angulartics2#5]
I'm using Angulartics2 with a project derived from angular2-webpack-starter and an seeing the following warnings: 

`
WARNING in ./~/angulartics2/index.js
Cannot find source file 'src/index.ts': Error: Cannot resolve 'file' or 'directory' ./src/index.ts in path/node_modules/angulartics2

WARNING in ./~/angulartics2/core/angulartics2On.js
Cannot find source file '../src/core/angulartics2On.ts': Error: Cannot resolve 'file' or 'directory' ../src/core/angulartics2On.ts in path/node_modules/angulartics2/core

WARNING in ./~/angulartics2/core/angulartics2.js
Cannot find source file '../src/core/angulartics2.ts': Error: Cannot resolve 'file' or 'directory' ../src/core/angulartics2.ts in path/node_modules/angulartics2/core
`

The warnings appear to come from the source maps, which reference *.ts files that are not included in the package.

**Comment by JonnyBGod** [comment]
What angular2 version are you trying with?

There are some fundamental changes with latest beta updates. I will they to update to the latest version as soon as possible.

**Comment by tbinkleyjones** [comment]
We are working with 2.0.0-beta.6

**Comment by JonnyBGod** [comment]
Ok found what is causing it.

angular2-webpack-starte webpack.config.js:

```
preLoaders: [
      // { test: /\.ts$/, loader: 'tslint-loader', exclude: [ helpers.root('node_modules') ] },
      // TODO(gdi2290): `exclude: [ helpers.root('node_modules/rxjs') ]` fixed with rxjs 5 beta.3 release
      { test: /\.js$/, loader: "source-map-loader", exclude: [ helpers.root('node_modules/rxjs') ] }
    ],
```

you can exclude paths from this loader.

Thing is that I don't think it is best practice to include src code that is not needed in production from a release version. So for now the release will stay as is.

you can easily exclude all node_modules libraries with: 

```
{ test: /\.js$/, loader: "source-map-loader", exclude: [/node_modules ] }
```

or if you still prefer to keep all other libraries use:

```
{ test: /\.js$/, loader: "source-map-loader", exclude: [ helpers.root('node_modules/rxjs'), /nodemodules\/angulartics2/ ] }
```

Hope it helps.

**Comment by tbinkleyjones** [comment]
Adding 
`, root('node_modules/angulartics2') `
to the source-map-loader config did the trick.
