### ISSUE TITLE
Ionic2 integration 

### ISSUE THREAD

**Issue by geoHeil** [angulartics/angulartics2#50]
Hi
How well does angulartics 2 integrate with ionic2 which itself relies on angular2?

**Comment by geoHeil** [comment]
I try to integrate it here https://github.com/geoHeil/ionic2Angulartics2 but initialization does not work out fine. Anyone has an idea what is wrong?

**Comment by geoHeil** [comment]
I am facing this problem http://stackoverflow.com/questions/38203479/angular2-rc-4-upgrade-breaks-test-platformstrategy-getbasehref-is-not-a-functi with RC-3

**Comment by JonnyBGod** [comment]
Hi,

could you update your code to work with latest version and Angular RC6.

Let me know if you still get an error and share a repo for testing please.

**Comment by rodneyjoyce** [comment]
Were you able to get Ionic2 final and Angulartics working together?

**Comment by jcyh0120** [comment]
hope it can support ionic, too.

**Comment by HarelM** [comment]
Has anyone been able to make this work? I'm in the process of creating an app from my site code and would like to have this too.

**Comment by HarelM** [comment]
Has this been resolved? Is there a provider I can use?

**Comment by davoam** [comment]
It works with Capacitor 2 (which is used by ionic), Angular 10. 

On Android and Web it works without any changes. 

For iOS I did some changes describe here https://stackoverflow.com/a/14154554/2560220

**Comment by HarelM** [comment]
I was able to make it work back then, I don't exactly remember how, I can probably share my code if anyone needs this...
