### ISSUE TITLE
How do you disable tracking?

### ISSUE THREAD

**Issue by mpetkov** [angulartics/angulartics2#51]
I have an application that will be deployed in multiple environments.  Actual tracking will happen only on one environment.  The envrionment that will have tracking will let the app know with a boolean to turn on analytics.  How can I get this plugin to disable analytics based on an external variable that is passed to the application?

**Comment by JonnyBGod** [comment]
You can use ```this.angulartics2.developerMode(true)``` to disable angulartics2.

**Comment by timelf123** [comment]
Passing config variables based on env is outside of the scope of Angulartics2. That being said here are some third party packages that will help you:

Depending on build env
  - [Gulp](https://github.com/guzart/gulp-ng-constant)
  - [Grunt](https://github.com/werk85/grunt-ng-constant)
  - [NodeJS](https://www.npmjs.com/package/ng-constant)
  - Webpack below
```
webpack.DefinePlugin

//webpack.config.js
...

let config = {};
if (process.env.NODE_ENV == 'development') {
  config.analyticsOn = false;
} else {
  config.analyticsOn = false;
}

// or with env variables

const ANALYTICS_ON = process.env.ANALYTICS-ON;

...

plugins:[
  new webpack.DefinePlugin({config: config})
]
...
```

**Comment by harryjubb** [comment]
I tried `this.angulartics2.developerMode(true)` as suggested by @JonnyBGod. I put that line in the `constructor` of my `AppComponent`, which works, except it still tracks the initial page view (but not subsequent events).

Is there a place I could put the `this.angulartics2.developerMode(true)` that doesn't track the initial page view?

**Comment by jwcm488** [comment]
@harryjubb I put my check for `environment.production` in the constructor of my AppComponent and it seems to work properly now. Also if you're using Google Analytics, make sure when you put the script tag to your `index.html` that you remove the `ga('send', 'pageview');` line.

**Comment by magnattic** [comment]
How do I do this with Angulartics2Piwik? It doesn't have the public method 'developerMode()'.

**Comment by scttcper** [comment]
developermode is on the angulartics2 provider it can also be set on forRoot
```
Angulartics2Module.forRoot([providers], {
  developerMode: True
}),
```

**Comment by magnattic** [comment]
Hm, unfortunately that's too early for me. I need to set this depending on a query parameter in the URL, which I cannot access during bootstrapping of the module.

**Comment by scttcper** [comment]
yeah the angulartics2 service.
```
angulartics2.settings. developerMode = true;
```

**Comment by enniob** [comment]
@scttcper do you know if there are any issue with the developerMode flag? I have it setup on my app.modules.ts forRoot to true but I can still see the pages from my development when I login to google Analytics.
