### ISSUE TITLE
Update to RC5

### ISSUE THREAD

**Issue by rolandoldengarm** [angulartics/angulartics2#52]
I don't believe the repository is compatible with RC5.

**Comment by 281330** [comment]
I think it is compatible.  You just need to set it up like this:

In `app.module.ts`, 

`import { Angulartics2 } from 'angulartics2';`

Then in your `providers: [Angulartics2]`

I am able to get it to work for pageviews.

**Comment by kdmaris** [comment]
I think it is compatible. You just need to set it up like this:

In app.module.ts,

import { Angulartics2 } from 'angulartics2';

Then in your providers: [Angulartics2]

I am able to get it to work for pageviews.

**Comment by rolandoldengarm** [comment]
It does not work in RC5 in my case, related to this issue: https://github.com/angulartics/angulartics2/issues/46

I've ditched Angulartics completely due to lack of support and writing my own service now, hooking into router events which is working like a charm.

**Comment by timelf123** [comment]
This is an open source project. We obviously want to support the latest RC but cannot do so without help from the community. 

@rolandoldengarm isn't this an upstream breaking change? https://github.com/angular/angular/issues/10909

**Comment by JonnyBGod** [comment]
@rolandoldengarm As @timelf123 mentioned this is an open source community project and while we want to keep up with every update, there are still constrains like lack of time due to our own jobs/projects, upstream bugs and that fact that Angular2 is being heavily changed and a lot of breaking changes have been launched.

That said, we expect to have a fully working and as much support as possible when Angular2 is officially released. Until then, we will try to keep up but give no guarantees of the timeframes for updates and even if every Angular2 RC release will be supported. As you are aware, there are upstream bugs that prevent us from delivering a fully working project. We want to try and keep Angularities2 router agnostic as much as possible and that is a problem at the moment.

There is always space for other similar projects like your own, but in my opinion we could do much better if everyone worked together to improve Angulartics2. We would welcome any PR and plugin that improves Angulartics2.

If you are interested in helping out you can always make a PR or even let me know if you want to me an active collaborator and I will add you to the list.

**Comment by NathanWalker** [comment]
@rolandoldengarm 
> I've ditched Angulartics completely due to lack of support and writing my own service now, hooking into router events which is working like a charm.

This unfortunately is the type of comment that is very poor taste.
If you are writing your *own* service, please help make this library better by helping submit your working service idea. 

Besides, that is how this library has come together. By the community. Be a part.

**Comment by rolandoldengarm** [comment]
Sorry to have sounded harsh, totally not my intention.

I totally understand that this is a community effort. However, there should be somebody monitoring the issues, and adding labels, etc. By putting it on Github doesn't mean it will improve itself over time.

I come across too many abandoned github repositories where nobody looks at the issues and then it just becomes a mess. And I don't want to waste my time on repo's that have no owner/owners. As recent issues were not updated / replied to here, I concluded this repo was abandoned as well.

To come back to the original issue: The location change event does no longer fire since RC4, see this issue: https://github.com/angulartics/angulartics2/issues/46
As @NathanWalker says angulartics will/should not rely on Router, Location event does not fire, Angulartics have to wait until that Angular issue will be fixed.

Sorry again for upsetting you. I appreciate all the replies here. I'm more than happy to submit a PR as soon as the angular2 issue has been fixed, to make it compatible with RC5!

**Comment by NathanWalker** [comment]
@rolandoldengarm there is a wonderful solution here:
https://github.com/angulartics/angulartics2/issues/29#issuecomment-220213585

**Comment by rolandoldengarm** [comment]
@NathanWalker Nice one. Would you like to have that integrated in Angulartics? I.e. add that class to the solution, and provide documentation how to use it?
I've created a new plunkr based on the previous issue, and linked it here: https://github.com/angular/angular/issues/10963

I think it's better to wait until this ng issue is solved, and not introduce workarounds in Angulartics. What do you think?

**Comment by JonnyBGod** [comment]
I think we could provide a branch with that solution for easy use and keep master as is.

**Comment by rolandoldengarm** [comment]
... and publish that branch to NPM as well? What would the naming convention be in that case? "angulartics2@beta" ?
More than happy to create that branch, but only if I can reference it from our application via NPM :)

**Comment by JonnyBGod** [comment]
No need for NPM register in my opinion. Just note on read how to use it from package.json directly from GitHub. It is a temporary fix.

Something like:
```
{
    "dependencies": {
        "angulartics2": "https://github.com/angulartics/angulartics2.git#temporary-router-fix"
    }
}
```

**Comment by rolandoldengarm** [comment]
What is your build process?
I run into a couple of issues when adding package to my application via Git:
- no version in package.json (fixed)
- no files in the node_modules (fixed by removing .npmignore)
- no transpiled javascript (how to fix?)

See my repo with the fix implemented: https://github.com/rolandoldengarm/angulartics2/tree/rc5-router-fix

Do you have some readme how you usually publish to NPM? So I can mimick that? @JonnyBGod

**Comment by JonnyBGod** [comment]
I am using https://github.com/semantic-release/semantic-release with travis for automated build and distribution process. For this case this might not be a good idea, a manual build should be better if your going for a temporary fixe branch. Instead do:

- manual version on package.json
- comment out *.js (keep node_modules ignored) (might also need to comment out *.d.ts, typings, ./providers, ./core, ./index.js)
- npm run build

It is very late here at the moment and I am not at my laptop, so not really sure of the full process. Test a bit with different .gitignore settings you should get there easily.

**Comment by rolandoldengarm** [comment]
@JonnyBGod got it all hooked up now, but now get this error?

browser_adapter.js:84 EXCEPTION: Error: Uncaught (in promise): ReferenceError: _gaq is not defined

... at the line where it checks if (_gaq)

I'm using the current Google Analytics code that does not define _gaq:

````
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-xxx', 'auto');
  ga('send', 'pageview');

</script>
````
I will fix that by adding if typeof (_gaq) !== 'undefined' but this issue does not seem to be related to RC5?

**Comment by JonnyBGod** [comment]
That is a known bug, check https://github.com/angulartics/angulartics2/issues/11.

If you think you can fix would be cool.

**Comment by rolandoldengarm** [comment]
I've fixed the issue by checking if _gaq is undefined. However, _gac maybe imported async, so it would be a timing issue. In my case _gaq is never defined, so it looks like it's no longer being used.

All working in our application! You can add it by adding this to your package.json dependencies & run npm install

"angulartics2": "https://github.com/rolandoldengarm/angulartics2.git#rc5-router-fix"

**Comment by pbazurin-softheme** [comment]
@rolandoldengarm Thanks for the fix in your fork)
I faced a problem - index.js is missing in root folder after 'run npm install'.
Could you please add it? (to be consistent with original package)

**Comment by lunks** [comment]
Is there any way I can hide their profile without disliking them? It's
getting really cluttered!

**Comment by rolandoldengarm** [comment]
@pbazurin-softheme Done.

**Comment by JonnyBGod** [comment]
fixed by https://github.com/angulartics/angulartics2/commit/5c89f50ea7511c8a5b9f4fc131a0b40b883536db
