### ISSUE TITLE
with latest 1.1.4: angulartics2.d.ts(1,1): error TS2688: Cannot find type definition file for 'core-js'.

### ISSUE THREAD

**Issue by NathanWalker** [angulartics/angulartics2#57]
I'm seeing this with the latest release and rc.6 and Typescript 2.0.2:

> node_modules/angulartics2/src/core/angulartics2.d.ts(1,1): error TS2688: Cannot find type definition file for 'core-js'.

**Comment by JonnyBGod** [comment]
hum. can you try defining types on tsconfig.json?

```
{
  "compilerOptions": {
    ...
    "types": [
      "core-js",
      "jasmine"
    ]
  }...
}
```

**Comment by NathanWalker** [comment]
Good thoughts and thanks for the suggestion, but that causes this:
```
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'core-js'. (2688)
```

**Comment by JonnyBGod** [comment]
sorry @NathanWalker I will not be able to check this out until later today. Meanwhile can you test ```npm i --save @types/core-js```

**Comment by JonnyBGod** [comment]
@NathanWalker I just pushed a new release trying to fix typings issues can you test it?

**Comment by NathanWalker** [comment]
Thanks @JonnyBGod that fixed it! 👍
