### ISSUE TITLE
Invalid 'reference' directive syntax with 1.1.4

### ISSUE THREAD

**Issue by symbyte** [angulartics/angulartics2#58]
Getting the following error in my typescript (v1.8.10) compilation step for my build process: 

```
node_modules/angulartics2/src/core/angulartics2.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax.
```

Moving back to 1.1.3 the error is not present

**Comment by JonnyBGod** [comment]
1.1.4+ is compatible with Angular RC6 witch moved to typescript 2.x

If your using RC6 please update typescript and try again.
