### ISSUE TITLE
Using without router?

### ISSUE THREAD

**Issue by symbyte** [angulartics/angulartics2#60]
Is there any way to use this library without the angular 2 router? My application doesn't make use of this router and I'm finding myself bringing it in to my project just to keep from getting 'No provider for Location' and 'no provider for Router' errors from angular. I would prefer not to have to do this if possible.

**Comment by rolandoldengarm** [comment]
There is no way currently due to a bug in Angular2. For the entire discussion, see here: https://github.com/angulartics/angulartics2/issues/29

**Comment by JonnyBGod** [comment]
We can consider separating  page tracking from the event tracking service.

I will put this for discussion.

@NathanWalker @rolandoldengarm @timelf123 
How do you feel about this and ending with something like ```import { angulartics2, angulartics2PageTraking } from "angulartics2";``` ... ?

**Comment by JonnyBGod** [comment]
or maybe we could have a base service without page tracking and the core would extend the base.

```
// regular users with full functionality
import { angulartics2 } from "angulartics2";

// users that do not want page tracking
import { angulartics2Base } from "angulartics2";
```

**Comment by artaommahe** [comment]
@JonnyBGod does it mean that currently angulartics2 cant be used with anything except `@angular/router`? (ui-router with manual page tracking e.x.)

**Comment by JonnyBGod** [comment]
@artaommahe Currently Angulartics core imports ```@angular/router```. This does not necessarily means that it is impossible to use with other routers.

It is possible to trigger all events "manually" and this makes it possible to attach it to any other router, the down side being that you will still need to ship ```@angular/router``` with it even if your not using it.

I will need to reevaluate this soon. Not sure if the upstream bug preventing us from being router agnostic is fix by now. If not, we would go with one of the options I mentioned before in this thread.

**Comment by artaommahe** [comment]
@JonnyBGod 
> It is possible to trigger all events "manually"

how page view event can be called manually with angulartics2? cant find this in docs :( `$analytics.pageTrack(url)` from ng1 angulartics

**Comment by JonnyBGod** [comment]
```
import { Angulartics2 } from './angulartics2';

...
constructor(private angulartics2: Angulartics2) {
    this.angulartics2.next({ path, location });
}
...
```

**Comment by MatthiasDebaere** [comment]
Hello, I've just encountered this problem. So.... is there any update on this topic? Is it possible to use angulartics2 without using a router configuration?

**Comment by cmaart** [comment]
+1

**Comment by KatzoA** [comment]
If I understand correctly to use googleAnalytics I am obliged to use the router? Thanks

**Comment by JonnyBGod** [comment]
@KatzoA Yes, atm this library needs router to work.

**Comment by KatzoA** [comment]
@JonnyBGod thank you!

**Comment by sertal70** [comment]
+1

I'm trying to use angulartics2 in a Ionic2 project but it doesn't work because of Routers (Ionic doesn't use routes). Any update on this topic would be greatly appreciated, thanks!

**Comment by kevinnoll** [comment]
I am also trying to use it with the Ionic2 router

**Comment by spacepope** [comment]
angulartics2 looks so nice - what a pity that Ionic 2 users are left behind.. 
So thumbs up for a possibility to work without angular/router requirement. (i would be fine with tracking  pages manually)
👍

**Comment by kukac7** [comment]
please give me a https://github.com/ui-router/angular support! 😞

**Comment by scttcper** [comment]
added in 4.6.x https://github.com/angulartics/angulartics2/releases/tag/v4.6.0

**Comment by sertal70** [comment]
That's great! Thanks @scttcper !
