### ISSUE TITLE
How to tracking only production

### ISSUE THREAD

**Issue by inska** [angulartics/angulartics2#62]
Hi,

I am using angulartics2 with Angular 2.0.0-rc5 and webpack to track user activities and it works VERY well, and thank you. Only what I want to do is turn GA on when only production environment, not stage or development.

Is there any function or tricks to prevent tracking on stage environment?

Best,

**Comment by JonnyBGod** [comment]
you can use ```this.angulartics2.developerMode(true);``` to prevent angulartics2 from dispatching events to providers.

**Comment by timelf123** [comment]
@inska but you should be able to set a constant with webpack based on the env, then set the mode accordingly

**Comment by elenafedorets** [comment]
Hi! @JonnyBGod . I use angulartics2 6.0.0, the property developerMode() is deprecated and doesn't exist on type 'Angulartics2'. What property should I use for enable anaytics only in production?

**Comment by scttcper** [comment]
@elenafedorets set it in the settings passed to `forRoot` or change it w/ `this.angulartics2.settings.developerMode = true`
