### ISSUE TITLE
angulartics angulartics2On directive not working with loadChildren routes in angular2.0

### ISSUE THREAD

**Issue by mounikaseelam20** [angulartics/angulartics2#63]
I am using angular2.0 for my application

I installed angulartics2 using _npm install angulartics2 --save_ and imported them in the app module. Every thing worked fine. Later, I used lazyloading for one module and now angulartic2On is not working.Following is my code.

> //app.module.ts

```
`import { Angulartics2 } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google- analytics';
import { BrowserModule } from '@angular/platform-browser';
import {CommonModule} from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
CommonModule,
FormsModule,
HttpModule,
RouterModule,

Angulartics2Module.forRoot(),
AppRouteRoot
],
providers: [
Angulartics2GoogleAnalytics 
],
bootstrap: [AppComponent]
})`
```

> //app.component.ts

```
` import { Component } from '@angular/core';

import { Angulartics2 } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google-analytics';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(angulartics2: Angulartics2, angulartics2GoogleAnalytics:    Angulartics2GoogleAnalytics) {}

 }`
```

> //app.routes.ts

`import { Routes, RouterModule } from '@angular/router';

import {ModuleWithProviders} from '@angular/core';

import {AppComponent} from './app.component';

export const AppRoutes: Routes = [
{ path: '', component: AppComponent},
{ path: 'about', loadChildren : 'app/about/about.module' },
];

export const AppRouteRoot:ModuleWithProviders = RouterModule.forRoot(AppRoutes, { useHash: true });`

> //app.component.html

`<h1>
  {{title}}
</h1>
<button angulartics2On="click" angularticsEvent="DownloadClick" angularticsCategory="APP">button inside app component</button>
<router-outlet></router-outlet>`

> //about.module.ts

`    

```
// import { Angulartics2Module } from 'angulartics2';
// import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google-   analytics';
// import { Angulartics2On } from 'angulartics2/src/core/angulartics2On';
 import { NgModule }       from '@angular/core';
 import { CommonModule } from '@angular/common';
 import { FormsModule} from '@angular/forms';
 import { HttpModule } from '@angular/http';
 import { RouterModule } from '@angular/router';
 import {AboutComponent} from './about.component';

import {AboutRouting} from './about.routes'

  @NgModule({
     declarations: [

    AboutComponent
//  ,
//   Angulartics2On


],
providers: [
    // Angulartics2GoogleAnalytics

],
imports: [
    CommonModule,    

    RouterModule,
    FormsModule,
    HttpModule,

    AboutRouting,
    // Angulartics2Module.forRoot(),
    // Angulartics2On

]
 })
   export default class AboutModule { }`
```

> //about.component.ts

` 
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
    })
export class AboutComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

 } 
`

> //about.routes.ts

```
 import { Routes, RouterModule } from '@angular/router';
    import {ModuleWithProviders} from '@angular/core';
    import {AppComponent} from './app.component';
    export const AppRoutes: Routes = [
    { path: '', component: AppComponent},
    { path: 'about', loadChildren : 'app/about/about.module' },
    ];
    export const AppRouteRoot:ModuleWithProviders = RouterModule.forRoot(AppRoutes, { useHash:   true });
```

> //about.component.html

```
`<p>
  about works!
</p>
<button type="button" (click)="fnTrack()" angulartics2On="click" angularticsEvent="DownloadClick"   angularticsCategory="ABOUT">About   Click</button>`
```

> //package.json

```
`...

"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
     "@angular/platform-browser": "2.0.0",
     "@angular/platform-browser-dynamic": "2.0.0",
     "@angular/router": "3.0.0",
    "angulartics2": "^1.1.9",
    "core-js": "^2.4.1",
    "process-nextick-args": "^1.0.7",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
   "zone.js": "^0.6.23"
  }

...`
```

is there any way to enable angulartics2 in lazy Routing

Thanks in advance

**Comment by JonnyBGod** [comment]
Have you tried declaring ```Angulartics2On``` in about.module? I see it there but commented out.

**Comment by mounikaseelam20** [comment]
If I declare `Angulartics2On`  in about.module I am getting the following error


> error_handler.js:45 EXCEPTION: Uncaught (in promise): Error: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule.ErrorHandler.handleError @ error_handler.js:45next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
error_handler.js:50 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
error_handler.js:51 Error: Uncaught (in promise): Error: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule.
    at resolvePromise (zone.js:429)
    at zone.js:406
    at ZoneDelegate.invoke (zone.js:203)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:202)
    at Zone.run (zone.js:96)
    at zone.js:462
    at ZoneDelegate.invokeTask (zone.js:236)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:235)ErrorHandler.handleError @ error_handler.js:51next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
zone.js:355 Unhandled Promise rejection: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule. ; Zone: angular ; Task: Promise.then ; Value: Error: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule.(…) Error: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule.
    at CompileMetadataResolver._addTypeToModule (http://localhost:4200/main.bundle.js:25090:19)
    at CompileMetadataResolver._addDirectiveToModule (http://localhost:4200/main.bundle.js:25112:18)
    at http://localhost:4200/main.bundle.js:25002:31
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:24995:49)
    at RuntimeCompiler._compileComponents (http://localhost:4200/main.bundle.js:37398:47)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:4200/main.bundle.js:37336:37)
    at RuntimeCompiler.compileModuleAsync (http://localhost:4200/main.bundle.js:37327:21)
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:4200/main.bundle.js:37645:31)
    at http://localhost:4200/main.bundle.js:58526:60consoleError @ zone.js:355_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386
zone.js:357 Error: Uncaught (in promise): Error: Type Angulartics2On is part of the declarations of 2 modules: Angulartics2Module and AboutModule! Please consider moving Angulartics2On to a higher module that imports Angulartics2Module and AboutModule. You can also create a new NgModule that exports and includes Angulartics2On then import that NgModule in Angulartics2Module and AboutModule.(…)

and if I include `Angulartics2Module`  in about.module getting following error

> error_handler.js:45 EXCEPTION: Uncaught (in promise): Error: Angulartics2Module already loaded; Import in root module only.ErrorHandler.handleError @ error_handler.js:45next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
error_handler.js:50 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
error_handler.js:51 Error: Uncaught (in promise): Error: Angulartics2Module already loaded; Import in root module only.
    at resolvePromise (zone.js:429)
    at zone.js:406
    at ZoneDelegate.invoke (zone.js:203)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:202)
    at Zone.run (zone.js:96)
    at zone.js:462
    at ZoneDelegate.invokeTask (zone.js:236)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:235)ErrorHandler.handleError @ error_handler.js:51next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386
zone.js:355 Unhandled Promise rejection: Angulartics2Module already loaded; Import in root module only. ; Zone: angular ; Task: Promise.then ; Value: Error: Angulartics2Module already loaded; Import in root module only.(…) Error: Angulartics2Module already loaded; Import in root module only.
    at new Angulartics2Module (http://localhost:4200/main.bundle.js:33547:19)
    at NgModuleInjector.AboutModuleInjector.createInternal (AboutModule.ngfactory.js:74:32)
    at NgModuleInjector.create (http://localhost:4200/main.bundle.js:42415:76)
    at NgModuleFactory.create (http://localhost:4200/main.bundle.js:42400:18)
    at MapSubscriber.project (http://localhost:4200/main.bundle.js:22428:25)
    at MapSubscriber._next (http://localhost:4200/main.bundle.js:22993:35)
    at MapSubscriber.Subscriber.next (http://localhost:4200/main.bundle.js:6557:18)
    at http://localhost:4200/main.bundle.js:48854:36
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:72288:28)
    at Object.onInvoke (http://localhost:4200/main.bundle.js:59548:37)consoleError @ zone.js:355_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386
zone.js:357 Error: Uncaught (in promise): Error: Angulartics2Module already loaded; Import in root module only.(…)

**Comment by rolandoldengarm** [comment]
You should not import both the module as well as put it in declarations. Just importing the Angulartics module should be enough.

**Comment by aedensixty** [comment]
I am getting the same problem.  Getting error 'Can't bind to 'angularticsProperties' since it isn't a known property of 'a'. ("()"' on lazy loaded elements. 

Stripped down version of code:

// App.module.ts
`@NgModule({
    imports: [
        Angulartics2Module.forRoot()
    ],
    providers: [Angulartics2GoogleAnalytics],
    bootstrap: [AppComponent]
})`

// app.component.ts
`@Component({
    selector: 'as-main-app',
    templateUrl: 'app/app.html'
})
export class AppComponent{
    constructor(
        angulartics2: Angulartics2,
        angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics {
    }
}`

// lazy.module.ts
`import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { SharedModule }  from '../../shared/shared.module';
import {LazyComponent} from './lazy.component';

import { routing } from './lazy.routes';

@NgModule({
    imports: [
        SharedModule, routing
    ],
    declarations: [
        LazyComponent
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class LazyModule {
}`

// lazy.routes
`import {LazyComponent} from './lazy.component';
import { Routes, RouterModule } from '@angular/router';

export const LazyRoutes: Routes = [
    {path: '', component: LazyComponent }
];

export const routing = RouterModule.forChild(LazyRoutes);

export const LazyLazyRoutes: Routes = [
  { path: 'lazy', loadChildren: 'app/pages/lazy/lazy.module#LazyModule' }
];`

// lazy.html
`<a angulartics2On="click" angularticsEvent="click"
        angularticsCategory="read-more" angularticsProperties="({label: 'read-more')">Read More</a>`

If I try to import it in the lazy.module or the lazy.component or a shared.module I get the error it has already been defined in a module as above.  Then any other time I get the template error that 'Can't bind to 'angularticsProperties' since it isn't a known property of 'a'. ("()"'.  On a non-lazy loaded template I do not need to reimport and it works fine???

**Comment by sudheerec107** [comment]
I am facing same above issue.

**Comment by kimaina** [comment]
I am facing the same issue... this should be given priority

**Comment by rolandoldengarm** [comment]
Can anyone share a plunkr? @kimaina maybe?

**Comment by kimaina** [comment]
Thanks @rolandoldengarm let me do this, give me few minutes

**Comment by kimaina** [comment]
hey there is no angulartics2 package on plunker and cdnjs.. created a request in cdnjs, will take sometimes before this get done

**Comment by dongtong** [comment]
Hi all,

The following is solution.

cc) @mounikaseelam20 @JonnyBGod @rolandoldengarm @aedensixty @sudheerec107 

I think you could create common shared component, directive, or pipe in one module, then export that shared module

```
// shared.module.ts
import { NgModule }                      from '@angular/core';
import { BrowserModule }         from '@angular/platform-browser';

import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google- analytics';

@NgModule({
    imports: [ BrowserModule ],
    declarations: [
        Angulartics2GoogleAnalytics
    ],
    exports: [ Angulartics2GoogleAnalytics ]
})

export class SharedModule {}

// about.module.ts

import { NgModule }       from '@angular/core';
 import { CommonModule } from '@angular/common';
 import { FormsModule} from '@angular/forms';
 import { HttpModule } from '@angular/http';
 import { RouterModule } from '@angular/router';
 import {AboutComponent} from './about.component';

import {AboutRouting} from './about.routes'

import { SharedModule } from '******your path*****';

  @NgModule({
     declarations: [

    AboutComponent

],
providers: [],
imports: [
    CommonModule,    

    RouterModule,
    FormsModule,
    HttpModule,

    AboutRouting,
    SharedModule //******************

]
 })
   export default class AboutModule { }


// app.module.ts

`import { Angulartics2 } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google- analytics';
import { BrowserModule } from '@angular/platform-browser';
import {CommonModule} from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { SharedModule } from '******your path*****';

@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
CommonModule,
FormsModule,
HttpModule,
RouterModule,
SharedModule, // **************
AppRouteRoot
],
providers: [
Angulartics2GoogleAnalytics 
],
bootstrap: [AppComponent]
})
```

**Comment by daveriedstra** [comment]
@dongtong Unfortunately using a shared module to declare the Angulartics2On directive fails with the same message: `Error: Type Angulartics2On is part of the declarations of 2 modules: SharedModule and Angulartics2Module!`

I'm having the exact same symptoms as @aedensixty describes.

**Comment by dongtong** [comment]
@daveriedstra

I have same issue "Error: Type Angulartics2On is part of the declarations of 2 modules: SharedModule and Angulartics2Module!", because of you extracted shared module failed. you should make sure that you want to extract part is independent.

**Comment by borntodesign** [comment]
@dongtong @daveriedstra whats the downside of importing Angulartics2Module, then exporting it again in SharedModule?

**Comment by daveriedstra** [comment]
@borntodesign Importing Angulartics2Module in SharedModule (or anywhere other than root) gives `Error: Angulartics2Module already loaded; Import in root module only`. I get this whether or not I call `Angulartics2Module.forRoot()` in the SharedModule imports, and also whether or not I've already imported `Angulartics2Module.forRoot()` in the root module.

shared.module.ts:
```
import { NgModule } from '@angular/core';
import { Angulartics2Module } from 'angulartics2';

@NgModule({
	imports: [
		Angulartics2Module.forRoot()
	],
	exports : [
		Angulartics2Module
	]
})
export class SharedModule {} 
```

@dongtong Sorry, I'm not sure what you're suggesting.

**Comment by borntodesign** [comment]
I have this working just loose the .forRoot() part. Just make sure you
aren't importing your shared module into your app module of course.

**Comment by daveriedstra** [comment]
@borntodesign I still get the same error. Here's my setup:

- `AppModule` provides `Angulartics2GoogleAnalytics`, imports `PageFooterModule`, and `AppRoutingModule` which handles lazy loading, currently *not* importing `Angulartics2Module.forRoot()`
- `SharedModule` imports `Angulartics2Module`, provides `Angulartics2`, exports `Angulartics2Module`
- `HomeModule`, `NavMenuModule`, `PageFooterModule`, and other lazy route modules import `SharedModule`
- route modules import `NavMenuModule`

Without `SharedModule` or `AppModule` providing `Angulartics2`, I get `No provider for Angulartics2`.

**Comment by borntodesign** [comment]
That's how I have it set up, although the only difference being my app
module provides angulartics2 not my shared module. It is getting a lot of
updates. Make sure you are using the latest version...

**Comment by daveriedstra** [comment]
@borntodesign Thanks for the reminder. Just updated to 1.4.1 from 1.1.12 and even after moving the `Angulartics2` provision to `AppModule` I get the same error.

**Comment by spicywhitefish** [comment]
My lazy routes setup is working, but only if I ignore `Angulartics2Module`. My SharedModule declares and exports the `Angulartics2On` directive, while my MainModule provides Angulartics2 services.

Proposed Solution: adding a `forChild()` method to `Angulartics2Module` only exports the `Angulartics2On`.

**Comment by stephsavoie** [comment]
I'm also facing the same issue.  I followed configuration steps on the project page.  I have a feature module that is lazy-loaded. GA pageviews are working on both root and child routes and GA event tracking in my main module are working fine as well.  But event tracking on my feature module are not sending the tracking data as expected

I tried to eliminate the feature module so I declared all it's services and components in my app module.  For routes, I merged them with the main routes in my app module

No console errors in any way and everything else is working fine.

I tried @borntodesign solution but "No providers" in console.

I'm used Angular CLI to setup my project.  Here's my package.json file for version info : 

```
{
  "name": "test-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/router": "^3.1.0",
    "angulartics2": "^1.4.3",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.1.0",
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.20-4",
    "codelyzer": "~1.0.0-beta.3",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
}
```

Any input is appreciated.

**Comment by JonnyBGod** [comment]
Please test this with latest release [v1.5.0](https://github.com/angulartics/angulartics2/releases/tag/v1.5.0)

**Comment by daveriedstra** [comment]
@JonnyBGod it appears to be working for my application. Tested in three lazy modules and everything's working normally as far as I can tell. Many thanks for addressing this!

**Comment by daveriedstra** [comment]
@JonnyBGod whoops, looks like I spoke too soon. Angulartics2 isn't actually making any analytics calls (nothing from route changes, click events, or `eventTrack.next()` calls). 

my output from google's `anaglytics_debug.js` is
```
Initializing Google Analytics.
Running command: ga("create", "UA-xxxxxxxx-x", "none")
Creating new tracker: t0
Registered new plugin: ga(provide, "render", Function)
```
and then nothing else. If I restore the `ga('send', 'pageview')` to the google snippet, its call goes through fine. I'm pretty sure my configuration is correct:

```
// AppModule:
@NgModule({
	providers: [ ... ],
	imports: [
		UniversalModule,
		AppRoutingModule,
		Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ]),
		...
	],
	declarations: [ AppComponent ],
	bootstrap: [ AppComponent ]
})
export class AppModule {}


// HomeModule (lazy):
@NgModule({
	imports: [
		HomeRoutingModule,
		Angulartics2Module.forChild(),
		...
	],
	declarations: [ HomeComponent ]
})
export class HomeModule {}
```

**Comment by JonnyBGod** [comment]
Hum.. That is odd. I have tested to make sure that * Angulartics2GoogleAnalytics* Service was getting the events with similar setup and also testes the events from *Angulartics2On* in a lazy loaded module were working.

**Comment by JonnyBGod** [comment]
Can you hardcode a console.log on the **pageTrack()** function for angulartics2-ga.js and see if they are getting there?

Have you imported Angulartics2 in you main component and ```contractor(public angulartics2: Angulartics2) {}``` ?

**Comment by daveriedstra** [comment]
angulartics2 is imported & injected into my main component (AppComponent) and a few others to test. Should it be injected like that for each component where it's used in the template, or is it fine just in the main component?

I've added console statements to **pageTrack()** and to the **Angulartics2GoogleAnalytics** constructor, and neither are called...

**Comment by stephsavoie** [comment]
Also tried new version and like @daveriedstra results, nothing happens.  Followed documentation two times to be sure.

**Comment by JonnyBGod** [comment]
I works if you do:

```
constructor(public angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {}
```

in you main component.

I am trying to figure out a way to avoid the need for this.

**Comment by stephsavoie** [comment]
@JonnyBGod Just tried your solution and it seems to be working great so far.  I'll wait for your final thought about this requirement.

**Comment by JonnyBGod** [comment]
Lets keep it this way for now. I will need some time to consult with others to see if there is a better way of initialising the used Providers. I will update the docs.

So for now we need to import and initialise every provider in the main component.
