### ISSUE TITLE
Application bootstrap fails when AdblockPlus has tracking disabled

### ISSUE THREAD

**Issue by martinhristov** [angulartics/angulartics2#69]
When AdblockPlus is enabled and it's "Disable Tracking" feature is turned on, then the application bootstrap fails.

I get the following errors in my console:
```
analytics.js:3 GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT

zone.js?1477305267073:1241 GET http://localhost:5555/node_modules/angulartics2/src/providers/angulartics2-google-analytics.js net::ERR_BLOCKED_BY_CLIENT

(index):48 Error: Error: XHR error loading http://localhost:5555/node_modules/angulartics2/src/providers/angulartics2-google-analytics.js(…) "Error bootstrapping application."
```

**Comment by martinhristov** [comment]
I saw there was the same issue with Angulartics for Angular 1.x (https://github.com/angulartics/angulartics/issues/58)

The same workaround with renaming the angulartics2-google-analytics.js file to anything not containing "google analytics" in its name (i.e. angulartics2-ga.js) seems to do the job here, as well.

**Comment by martinhristov** [comment]
I created a pull request (https://github.com/angulartics/angulartics2/pull/70) if you think the same workaround can be applied here.

**Comment by timelf123** [comment]
The ultimate solution is to bundle your assets, but renaming is a decent workaround until the new filename is blacklisted again

**Comment by martinhristov** [comment]
@timelf123 Thanks. For all but the dev environment it is going to be bundled and for dev it's not an issue to turn Ad blockers off.
