### ISSUE TITLE
Cannot import angulartics2 1.2.0

### ISSUE THREAD

**Issue by Simon-Briggs** [angulartics/angulartics2#72]
Hi, I just updated to the latest v 1.2.0 of angulartics2 and am no longer able to import the Module.
Have the import names now changed?

```
import { Angulartics2Module } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-ga';
```

**Comment by JonnyBGod** [comment]
Sorry broken build.

Please update to v1.2.2 and also change the way providers are imported:

```
import { Angulartics2GoogleAnalytics } from 'angulartics2/dist/providers';
```
