### ISSUE TITLE
angulartics2 Facebook Pixel provider 

### ISSUE THREAD

**Issue by sadaf-behbahani** [angulartics/angulartics2#75]
I am using angulartics2  in my app, and everything was working fine before the last commit "Add 
Facebook Pixel provider" 17d2b6b , and now I'm getting these errors : 

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\facebook\angulartics2-facebook.d.ts
(3,14): error TS1005: '=' expected.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\facebook\angulartics2-facebook.d.ts
(3,26): error TS1005: ';' expected.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\facebook\angulartics2-facebook.d.ts
(3,14): error TS2304: Cannot find name 'angulartics2'.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\facebook\angulartics2-facebook.d.ts
(3,28): error TS7008: Member 'Angulartics2' implicitly has an 'any' type.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\gtm\angulartics2-gtm.d.ts
(3,14): error TS1005: '=' expected.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\gtm\angulartics2-gtm.d.ts
(3,26): error TS1005: ';' expected.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\gtm\angulartics2-gtm.d.ts
(3,14): error TS2304: Cannot find name 'angulartics2'.

ERROR in D:\Users\sbehbaha\Documents\CALF\front\node_modules\angulartics2\dist\providers\gtm\angulartics2-gtm.d.ts
(3,28): error TS7008: Member 'Angulartics2' implicitly has an 'any' type.

Any idea ? 
Thanks in advance

**Comment by scttcper** [comment]
Its been ~ a year. Going to close this.
