### ISSUE TITLE
WIP Documentation

### ISSUE THREAD

**Issue by JonnyBGod** [angulartics/angulartics2#76]
Wiki based documentation.

---
Core:
- [ ] bootstrap
- [ ] angulartics2On

---
Providers:
- [x] Google Analytics
- [x] Google Tag Manager
- [ ] Kissmetrics
- [ ] Mixpanel
- [ ] Piwik
- [ ] Segment
- [ ] Baidu Analytics
- [ ] Facebook Pixel
- [ ] Application Insights

---
- [ ] Links to docs in README.md

**Comment by rohit-gupta** [comment]
I am trying to use angulartics2 with Mixpanel, is there any reference for it ? StackOverflow or something similar is fine, I will write some documentation afterwards.
