### ISSUE TITLE
Doku for PIWIK Settings

### ISSUE THREAD

**Issue by SimonaMilchevska** [angulartics/angulartics2#78]
Do you have Dokumentation how can I set up my piwik Settings in Order to track my Web-Site?

**Comment by literalpie** [comment]
One year later...

I don't believe there are any specific settings you need on the Piwik side besides the following:
> To track full URLs if there is a hash (#), make sure to enable settings=>websites=>settings=>page url fragments tracking in the Piwik dashboard.

Just make sure you follow the setup described [here](https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/piwik) to get things running on your app's side.
