### ISSUE TITLE
Call `create` from angulartics instead of the js snippet

### ISSUE THREAD

**Issue by altschuler** [angulartics/angulartics2#79]
### Feature request
Mechanism to call google analytics (or other providers I assume) `create` function manually. 

### Motivation
I'm working on a project in which we have separate tracking id's for dev/prod environments. Having to change the snippet on the `index.html`page is clumsy and inflexible. I would like a way to define the tracking id in my environment config and set it through angulartics.

Currently I have simply removed the `create` from `index.html` and then call `ga('create',  ... )` manually in a custom analytics service that wraps angulartics.

**Comment by JonnyBGod** [comment]
If I understand right, you need a public function in GA provider that just maps `ga('create', ... )`?

Something like:
```
public create(data:any): void {
  ga('create', data);
}
```

Is that it?

**Comment by altschuler** [comment]
Yes exactly. It's really simple. It's easy to do for Google in specific, I just wondered if and how to do it for other providers.

**Comment by JonnyBGod** [comment]
That is a good question... I am not familiar with most provider as I mostly use GA, GTM and Segment for my needs.

I will need some time to compile a list of commands for each provider and try to relate them all to understand better how they relate in features and how can we better implement these new features.

**Comment by dherges** [comment]
beware. this approach doesn't work in piwik or at last some versions of piwik which require the ``_paq`` to be initialised from global scope.

**Comment by altschuler** [comment]
@dherges Could that not be worked around like `_paq.apply(window, ...)` or something like that?

**Comment by dherges** [comment]
@altschuler you can try it out.

piwik provider does [`declare var _paq: any;`](https://github.com/angulartics/angulartics2/blob/master/src/providers/piwik/angulartics2-piwik.ts#L5) and then verifies that global variable in the constructor... so it needs to be there prior to `Angulartics2Piwik` being initialized.

**Comment by switch87** [comment]
I have forked the project to make a version without static javascript in the index.html file. This for the same reason you want to use it for.
Throwback is the code will be loaded only after bootstrapping angular. At the moment it only works for Google Analytics, but feel free to open a issue for the services you use (or to do a pull request).
the Google analytics version can already be installed using 'ngm install ngx-analytics'

https://github.com/SnakeByteDevelopment/angulartics2

**Comment by scttcper** [comment]
Injecting the analytics scripts from providers at runtime won't be supported.
