### ISSUE TITLE
Track event fired twice on initial page load

### ISSUE THREAD

**Issue by arimus** [angulartics/angulartics2#80]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

Initial page loads are triggering duplicate trackUrlChanges, thus sending multiple of the same page views to the server.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Basic installation of the library, wired up the tracking code in index.html page (show below). Note: I also tried to comment out the link tracking and create a subscription to the router myself and manually call this.angulartics2.pageTrack(newRoute, null) with the same result. It appears that developerMode is the only thing I can to to prevent that initial tracking event, which doesn't seem like the best approach.

```
  <script type="text/javascript">
    var _paq = _paq || [];
    //_paq.push(['trackPageView']); <-- commented out to prevent third request
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="//analytics.XXXXXX.com/piwik/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '1']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <noscript><p><img src="//analytics.XXXXXX.com/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
```

* **What is the expected behavior?**

For the initial page view to generate a single track event.

* **What is the motivation / use case for changing the behavior?**

So that it works as expected and doesn't cause multiple page views to show up on the server for a single page view.

* **Please tell us about your environment:**

- Angular version: 2.1.1
- Angular router version: 3.1.1
- Browser: Chrome - OSX - Version 54.0.2840.98 (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

See code below, but I believe that either the second trackUrlChange needs to be dropped, or if it is actuallyneeded in some circumstances (e.g certain router versions) then guard it with a flag to disable when necessary.

    Angulartics2.prototype.trackLocation = function (location, router) {
        var _this = this;
        router.events
            .filter(function (event) { return event instanceof router_1.NavigationEnd; })
            .subscribe(function (event) {
            if (!_this.settings.developerMode) {
                _this.trackUrlChange(event.urlAfterRedirects, location); // <-- this fires on first load
            }
        });
        if (!this.settings.developerMode) {
            this.trackUrlChange(location.path(), location); // <-- this also fires on first load
        }
    };

**Comment by JonnyBGod** [comment]
Than you for report.

It was indeed triggering twice.
