### ISSUE TITLE
Memory leak with ReplayEvent

### ISSUE THREAD

**Issue by Slyke** [angulartics/angulartics2#81]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
BUG

* **What is the current behavior?**
There is a memory leak with ReplayEvents
See: https://github.com/angulartics/angulartics2/blob/master/src/core/angulartics2.ts#L23 for an example.
Accoridng to RxJS's documentation, you should set a buffer size: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/replaysubject.md

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
ReplaySubjects in many of the files are unbounded (no maximum buffer size set) See: http://i.imgur.com/IfqPyil.png

* **What is the expected behavior?**
Set some upper limit on the buffer size (maybe 10?)

* **What is the motivation / use case for changing the behavior?**
Chrome will eventually crash due to running out of memory

* **Please tell us about your environment:**
Chrome

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Available on request.

**Comment by JonnyBGod** [comment]
Thanks for pointing it out!
