### ISSUE TITLE
Google Tag Assistant - Tracking included twice

### ISSUE THREAD

**Issue by borntodesign** [angulartics/angulartics2#82]
When I use Google Tag Assistant I seem to be getting double page views?
It is telling me the same tracking code is in my page twice?

http://www.hsimagazine.com/

**Comment by JonnyBGod** [comment]
What version of angulartics2 are you using?

**Comment by borntodesign** [comment]
"angulartics2": "^1.4.1",

**Comment by JonnyBGod** [comment]
That should be fixed since v1.5.1 please try the latest version v1.5.2.
