### ISSUE TITLE
Many trackers on one page

### ISSUE THREAD

**Issue by breslavsky** [angulartics/angulartics2#87]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Google support to send events to many trackers.
https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers

ga('create', 'UA-XXXXX-Y', 'auto');
ga('create', 'UA-XXXXX-Z', 'auto', 'clientTracker');

ga('send', 'pageview');
ga('clientTracker.send', 'pageview');

It is possible in angulartics2?

**Comment by silver2k** [comment]
Maybe? I need to do the same thing - and it's certainly supported in the Angulartics2GoogleAnalytics Provider via `angulartics2.settings.ga.additionalAccountNames` - however I can't work out how to set this array. The settings don't seem to be exposed - or I'm too stupid to work out how.
