### ISSUE TITLE
Is Facebook Pixel supported in ng2?

### ISSUE THREAD

**Issue by rodneyjoyce** [angulartics/angulartics2#89]
Hello,

I'm a bit confused - the ReadMe says that fb Pixel IS supported, but only GA and GA Tag MAnager have links that explain how to NPM in the additional package.

I can see there is an fb Pixel install for ng1 - where is this for ng2?

Thanks

**Comment by kaynz** [comment]
Hi,

Pixel is supported. You just need to to the default config at the end of the README and include your Pixel Snippet in your <head>.
