### ISSUE TITLE
import Angulartics2Module in all modules?

### ISSUE THREAD

**Issue by Flood** [angulartics/angulartics2#92]
Hi!

I've just installed Angulartics2 and tried it. In my AppModule I have 

``` 
Angulartics2Module.forRoot([Angulartics2GoogleTagManager]),
```
But when I want to use it in another component it complains about: Can't bind to 'angularticsCategory' since it isn't a known property of...

Do I have to import Angulartics2Module into every single module that I have? Why isn't it enough to import it in the AppModule, or my SharedModule?

**Comment by Flood** [comment]
Worked when I added it in my SharedModule (both import and export!)

**Comment by JonnyBGod** [comment]
```
Angulartics2Module.forRoot([Angulartics2GoogleTagManager]),
```

Should be only used in root module. That is why it is "forRoot".

Then in other modules or your shared module you import:

```
Angulartics2Module
```

**Comment by JonnyBGod** [comment]
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by Flood** [comment]
Yes, but I don't want to import it in all my modules. So instead I'm exporting it in Shared. Since all my modules already are importing Shared.
