### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by HaraldBregu** [angulartics/angulartics2#93]
When i install angulartics2 why i have this error in console? What it mean?

<img width="385" alt="schermata 2017-02-03 alle 11 33 11" src="https://cloud.githubusercontent.com/assets/1328379/22588102/b19f323c-ea04-11e6-8e0e-efd5ba82490d.png">
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by scttcper** [comment]
Make sure you have @angular/core installed that matches the desired range. This has since changed.
