### ISSUE TITLE
DeveloperMode not respected in event tracking

### ISSUE THREAD

**Issue by elvirdolic** [angulartics/angulartics2#97]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature/Bug

* **What is the current behavior?**
When setting developerMode to true then analytics is still working and events are send to Google Analytics. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
TurnOff all tracking possibility if developerMode is true and let's provide it trough the Module configuration. Setting this value in app.component is to late as the router events are already fired.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by elvirdolic** [comment]
any news on that? Can I provide a PR to fix that?

**Comment by JonnyBGod** [comment]
Please feel free to PR with fix. It would be very much appreciated.

**Comment by stevo-knievo** [comment]
Hi, I would love to help to fix it. But the only way I see it to fix it would be in the providers/ga it self. But I guess I should get fix (globally) in core/angulartics2, right? If you could get me a hint I might be able to fix it. Thanks Stevo

**Comment by AwsmOli** [comment]
I looked into how to fix it - and from the code, i think its already possible.

in your Module (eg. `app.module.ts`) where you import the `Angulartics2Module` use the second parameter in the `Angulartics2Module.forRoot` function to provide settings with `developerMode: true`

```
// app.module.ts
@NgModule({
	imports: [
                (...)
		Angulartics2Module.forRoot([Angulartics2GoogleAnalytics], { developerMode: !environment.production }),
                (...)
	],
	declarations: [
		(...)
	],
	providers: [
		(...)
	]
})
```

**Comment by scttcper** [comment]
yes @AwsmOli thanks for posting that. That wasn't available when this issue was opened and should fix the issue. Thanks!

**Comment by nikhilwason** [comment]
Hi. I'm also facing this problem and setting the value of developerMode in Angulartics2Module.forRoot() does not help.

However, one thing to note is that I'm using Angulartics2GoogleTagManager instead of Angulartics2GoogleAnalytics. Could that be causing this problem? Any pointers would be appreciated. Thanks.
