### ISSUE TITLE
With lastest version of Angular 2 and dependencies, google analytics not works

### ISSUE THREAD

**Issue by mmaryo** [angulartics/angulartics2#98]
* **I'm submitting a ...**
[] bug report

* **What is the current behavior?**
I write a simple projet with lastest deps, and as you can see, there is no google analytics event emitted 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

https://github.com/mmaryo/angular-2-angulartics2

npm install 
npm run

Install https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna in chrome 

open application in chrome and click on the button 
see in console that angulartics2 not emitted, but ga() event works

![screenshot 2017-02-21 15 33 26](https://cloud.githubusercontent.com/assets/1669985/23169648/e03c9610-f84c-11e6-941b-d1aa05c37036.png)

* **What is the expected behavior?**

the code in promo.component.ts is : 

https://github.com/mmaryo/angular-2-angulartics2/blob/master/src/app/components/home/promo/promo.component.ts

        ga('send', 'event', 'Submit', 'Home', 'MANUAL');
        this.ngtics.eventTrack.next({
            action: 'Submit',
            properties: {
                category: 'Home',
                label: "ngtics"
            }
        });

so we should see in console : 
event - Submit / HOME / Manual
event - Submit / HOME / ngtics

but last event (with ngtics) not emitted

* **Please tell us about your environment:**

        "@angular/common": "2.4.8",
        "@angular/compiler": "2.4.8",
        "@angular/core": "2.4.8",
        "@angular/forms": "2.4.8",
        "@angular/http": "2.4.8",
        "@angular/platform-browser": "2.4.8",
        "@angular/platform-browser-dynamic": "2.4.8",
        "@angular/router": "3.4.8",
        "angulartics2": "1.6.3",
        "bootstrap": "4.0.0-alpha.6",
        "core-js": "2.4.1",
        "rxjs": "5.2.0",
        "ts-helpers": "1.1.2",
        "zone.js": "0.7.7"

**Comment by Shireilia** [comment]
Same issue here with 2.4.10.

**Comment by hikirsch** [comment]
The code sample above is not injecting the `Angulartics2GoogleAnalytics` provider thus its never actually attaching.

**Comment by JonnyBGod** [comment]
can you try in injecting ```AngularticsService``` in you app component?

```
import { AnalyticsService } from 'shared/analytics/index';
...
export class AppComponent {
  constructor(public analytics: AnalyticsService){}
}
```

**Comment by returnlytom** [comment]
@JonnyBGod this is working for us:

> _app.module.ts_
```ts
import { NgModule } from '@angular/core';
...
import { Angulartics2Module, Angulartics2GoogleAnalytics, Angulartics2Mixpanel } from 'angulartics2';
import { Angulartics2Returnly } from './shared/utils/angulartics2-returnly'

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ...
    Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics, Angulartics2Mixpanel, Angulartics2Returnly ])
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

> _app.component.ts_
```ts
import { Component } from '@angular/core';

// https://github.com/angulartics/angulartics2/blob/master/README.md
import { Angulartics2GoogleAnalytics, Angulartics2Mixpanel } from 'angulartics2';
import { Angulartics2Returnly } from './shared/utils/angulartics2-returnly'


@Component({
  selector: 'products-flow',
  template: document.getElementById('app.component.html').innerHTML
})
export class AppComponent {

  constructor (
    angulartics2ga: Angulartics2GoogleAnalytics,
    angulartics2mp: Angulartics2Mixpanel,
    angulartics2returnly: Angulartics2Returnly
  ) {  }

}
```

**Comment by chriszrc** [comment]
Yes, I can confirm that using the 

```
angulartics2GoogleAnalytics
```

service directly does indeed work. But the documentation very clearly indicates that you can use the generic Angulartics2 service, and you should just be able to do :

```
this.angulartics2.eventTrack.next({ action: 'layerChange', properties: { category: 'Climate Health Maps', label: this.legendService.getFullThemeName(themeName) }});
```

but that never fires an actual http request, although it does add the event in the service queue. This works:

```
this.angulartics2ga.eventTrack('layerChange', { category: 'Climate Health Maps', label: this.legendService.getFullThemeName(themeName) });
```

**Comment by killerbytes** [comment]
Adding `Angulartics2GoogleAnalytics` works
```
import { Angulartics2, Angulartics2GoogleAnalytics } from 'angulartics2';
constructor(
    private angulartics2: Angulartics2,
    private angulartics2ga: Angulartics2GoogleAnalytics
) {}
```

**Comment by jelling** [comment]
Fwiw we've decided not to use this project since it appears to require calling the specific analytics tracker (ex. Angulartics for Google Analytics.) This doesn't make sense if one wants to abstract away the implementation.

**Comment by JonnyBGod** [comment]
@jelling not sure what you mean. The api is meant to abstract some common functions for analytics and then use a plugin system for you to plug in the providers you require.

What would be your desired behaviour?

**Comment by jelling** [comment]
@JonnyBGod 

My understanding of the value of this software is that it's a:

> Vendor-agnostic analytics for Angular2 applications

As such, I assumed it worked like this:

`ngtics.track({some event})`

This is helpful because we may use vendor X for analytics today (ex. Google Analytics) but switch to another later (Segment.com).

However, if one has to inject the Angulartics service **and**   the Google Analytics class, that defeats the purpose. And in that case, I don't understand  the value of the library.

For now, we've written a simple wrapper service (TrackingService) and injected that into our services / controllers. Inside that service, we call our analytics provider directly.

**Comment by JonnyBGod** [comment]
@jelling Sorry I am really not getting the diference here.

With Angulartics you can always change providers and/or use multiple providers.
The core service tries to make it provider agnostics but you always need to call the provider methods and for that you need to have their lib and an provider plugin to call it.

Can see your point.
